//! Represented aggro, threat and engagement for observed creatures.
//!
//! Moved out of the Session root under #599. Behaviour is preserved; the
//! canonical owner of this state is unchanged.

use super::*;

impl WorldSession {
    pub(crate) fn creature_aggro_radius_for_faction_template_like_cpp(
        &self,
        faction_template_id: u32,
        default_radius: f32,
    ) -> f32 {
        let (state, hub) = crate::session::split_world_entities_ref(self);
        state.creature_aggro_radius_for_faction_template_like_cpp(
            hub,
            faction_template_id,
            default_radius,
        )
    }
    pub(in crate::session) fn canonical_creature_threat_value_like_cpp(
        &self,
        creature_guid: ObjectGuid,
        attacker_guid: ObjectGuid,
    ) -> Option<f32> {
        let (state, hub) = crate::session::split_world_entities_ref(self);
        state.canonical_creature_threat_value_like_cpp(hub, creature_guid, attacker_guid)
    }
    pub(in crate::session) fn mirror_canonical_creature_threat_from_attacker_like_cpp(
        &mut self,
        creature_guid: ObjectGuid,
        attacker_guid: ObjectGuid,
        threat_value: f32,
    ) -> bool {
        let (state, mut hub) = crate::session::split_world_entities_mut(self);
        state.mirror_canonical_creature_threat_from_attacker_like_cpp(
            &mut hub,
            creature_guid,
            attacker_guid,
            threat_value,
        )
    }
    pub fn set_legacy_creature_aggro_config_like_cpp(
        &mut self,
        config: LegacyCreatureAggroConfigLikeCpp,
    ) {
        self.config.legacy_creature_aggro_config_like_cpp = config;
    }
    pub fn set_spell_threat_store(&mut self, store: Arc<SpellThreatStoreLikeCpp>) {
        self.catalogs.spell_catalogs.spell_threat_store = Some(store);
    }
    /// Represented single-target `Spell::HandleThreatSpells` pass. This runs
    /// once after all spell effects, unlike damage/heal threat which is
    /// generated by each individual effect.
    pub(in crate::session) fn apply_spell_initial_threat_like_cpp(
        &mut self,
        spell_id: i32,
        caster_guid: ObjectGuid,
        target_guid: ObjectGuid,
        is_positive: bool,
    ) {
        let Ok(spell_id_u32) = u32::try_from(spell_id) else {
            return;
        };
        let difficulty = self.core.current_map_difficulty_id_like_cpp();
        let difficulty_store = self.catalogs.difficulty_store().cloned();
        // C++ `Spell::HandleThreatSpells` performs this unconditional
        // `!SpellInfo::HasInitialAggro()` return before calling
        // `ThreatManager::AddThreat`. The latter's engaged-owner exception
        // applies to per-effect damage threat, not this cast-level bonus.
        if self.spell_store().is_some_and(|store| {
            store.has_attribute_for_difficulty_like_cpp(
                spell_id,
                difficulty,
                difficulty_store.as_deref(),
                1,
                wow_data::spell::attributes::SPELL_ATTR1_NO_THREAT,
            ) || store.has_attribute_for_difficulty_like_cpp(
                spell_id,
                difficulty,
                difficulty_store.as_deref(),
                2,
                wow_data::spell::attributes::SPELL_ATTR2_NO_INITIAL_THREAT,
            )
        }) {
            return;
        }
        if !is_positive
            && self.spell_store().is_some_and(|store| {
                store.has_attribute_for_difficulty_like_cpp(
                    spell_id,
                    difficulty,
                    difficulty_store.as_deref(),
                    4,
                    wow_data::spell::attributes::SPELL_ATTR4_NO_HARMFUL_THREAT,
                )
            })
        {
            return;
        }

        let threat_entry = self
            .catalogs
            .spell_threat_entry_like_cpp(spell_id_u32)
            .copied();
        let Some(base_amount) = ({
            let (s, h) = crate::session::split_world_entities_ref(self);
            s.spell_initial_threat_like_cpp(h, spell_id_u32, threat_entry, caster_guid)
        }) else {
            return;
        };
        if base_amount == 0.0 {
            return;
        }
        if !is_positive {
            let threat_outcome = self
                .core
                .mutate_world_creature(target_guid, |creature| {
                    if !creature.is_alive() {
                        return None;
                    }
                    if !creature
                        .creature
                        .unit()
                        .subsystems()
                        .combat
                        .owner_can_have_threat_list
                    {
                        return None;
                    }
                    let newly_engaged = !creature.creature.is_in_combat();
                    if newly_engaged {
                        creature.enter_combat(caster_guid);
                    }
                    let combat = &mut creature.creature.unit_mut().subsystems_mut().combat;
                    combat.add_threat(caster_guid, base_amount);
                    combat
                        .threat_value(caster_guid)
                        .map(|threat_value| (threat_value, newly_engaged))
                })
                .flatten();
            if let Some((threat_value, newly_engaged)) = threat_outcome {
                self.sync_represented_creature_threat_to_canonical_like_cpp(
                    target_guid,
                    caster_guid,
                    threat_value,
                );
                if newly_engaged {
                    self.publish_spell_pull_attack_start_like_cpp(target_guid, caster_guid);
                }
            }
            return;
        }

        // C++ positive-spell path:
        // `target->GetThreatManager().ForwardThreatForAssistingMe`.
        if self.spell_store().is_some_and(|store| {
            store.has_attribute_for_difficulty_like_cpp(
                spell_id,
                difficulty,
                difficulty_store.as_deref(),
                4,
                wow_data::spell::attributes::SPELL_ATTR4_NO_HELPFUL_THREAT,
            )
        }) {
            return;
        }
        let spell_school_mask = self.catalogs.spell_school_mask_for_difficulty_like_cpp(
            spell_id_u32,
            self.core.current_map_difficulty_id_like_cpp(),
        );
        let caster_school_threat_mod = if self.player_guid() == Some(caster_guid) {
            self.hydrate_canonical_threat_relevant_auras_like_cpp();
            self.core
                .mutate_canonical_player_like_cpp(|player| {
                    player
                        .unit()
                        .subsystems()
                        .auras
                        .total_aura_multiplier_by_misc_mask_like_cpp(
                            wow_data::spell::aura_types::SPELL_AURA_MOD_THREAT,
                            spell_school_mask,
                        )
                })
                .unwrap_or(1.0)
        } else {
            1.0
        };
        let amount = base_amount
            * threat_entry.map_or(1.0, |entry| entry.pct_mod)
            * caster_school_threat_mod;
        if amount == 0.0 {
            return;
        }
        let owner_guids = self.canonical_threatened_by_me_owner_guids_like_cpp(target_guid);
        let controlled_mask = UnitState::CONTROLLED.bits();
        let eligible_count = owner_guids
            .iter()
            .filter(|owner_guid| {
                self.core
                    .mutate_world_creature(**owner_guid, |creature| {
                        creature.is_alive()
                            && !creature.creature.unit().has_unit_state(controlled_mask)
                    })
                    .unwrap_or(false)
            })
            .count();
        let per_owner = (eligible_count != 0).then(|| amount / eligible_count as f32);
        for owner_guid in owner_guids {
            let threat_value = self
                .core
                .mutate_world_creature(owner_guid, |creature| {
                    if !creature.is_alive() {
                        return None;
                    }
                    let controlled = creature.creature.unit().has_unit_state(controlled_mask);
                    let combat = &mut creature.creature.unit_mut().subsystems_mut().combat;
                    combat.add_threat(
                        caster_guid,
                        if controlled {
                            0.0
                        } else {
                            per_owner.unwrap_or(0.0)
                        },
                    );
                    combat.threat_value(caster_guid)
                })
                .flatten();
            if let Some(threat_value) = threat_value {
                self.sync_represented_creature_threat_to_canonical_like_cpp(
                    owner_guid,
                    caster_guid,
                    threat_value,
                );
            }
        }
    }
    pub(in crate::session) fn canonical_threat_aura_snapshot_for_difficulty_like_cpp(
        &self,
        spell_id: i32,
        difficulty: u8,
        effect_mask: u32,
        represented_effect_amounts: &[RepresentedAuraEffectAmountLikeCpp],
    ) -> CanonicalThreatAuraSnapshotLikeCpp {
        let (state, hub) = crate::session::split_world_entities_ref(self);
        state.canonical_threat_aura_snapshot_for_difficulty_like_cpp(
            hub,
            spell_id,
            difficulty,
            effect_mask,
            represented_effect_amounts,
        )
    }
    pub(in crate::session) fn sync_canonical_threat_relevant_aura_like_cpp(
        &mut self,
        spell_id: i32,
        caster_guid: ObjectGuid,
        slot: u8,
        effect_mask: u32,
        represented_effect_amounts: &[RepresentedAuraEffectAmountLikeCpp],
        apply: bool,
    ) {
        if !apply {
            let Ok(spell_id) = u32::try_from(spell_id) else {
                return;
            };
            let _canonical = self
                .core
                .with_owned_player_mut_like_cpp(|player| {
                    player.remove_player_threat_aura_like_cpp(
                        spell_id,
                        caster_guid,
                        slot,
                        effect_mask,
                    );
                })
                .is_some();
            #[cfg(test)]
            if !_canonical && self.core.player_handle_like_cpp.is_none() {
                let _ = self.mutate_player_aura_subsystem_like_cpp(|auras| {
                    auras.remove_threat_snapshot_like_cpp(slot);
                    for effect_index in 0..u32::BITS {
                        let effect_bit = 1u32 << effect_index;
                        if effect_mask & effect_bit != 0 {
                            auras.remove_applied(wow_entities::AppliedAuraRef::new(
                                spell_id,
                                caster_guid,
                                slot,
                                effect_bit,
                            ));
                        }
                    }
                });
            }
            return;
        }
        let snapshot = crate::session::hub_ref(self)
            .player_aura_subsystem_snapshot_like_cpp()
            .and_then(|auras| auras.threat_snapshot_like_cpp(slot).cloned())
            .unwrap_or_else(|| {
                let difficulty = self.core.current_map_difficulty_id_like_cpp();
                self.canonical_threat_aura_snapshot_for_difficulty_like_cpp(
                    spell_id,
                    difficulty,
                    effect_mask,
                    represented_effect_amounts,
                )
            });
        let Ok(spell_id) = u32::try_from(spell_id) else {
            return;
        };
        let _canonical = self
            .core
            .with_owned_player_mut_like_cpp(|player| {
                player.apply_player_threat_aura_like_cpp(
                    spell_id,
                    caster_guid,
                    slot,
                    snapshot.clone(),
                );
            })
            .is_some();
        #[cfg(test)]
        if !_canonical && self.core.player_handle_like_cpp.is_none() {
            let _ = self.mutate_player_aura_subsystem_like_cpp(|auras| {
                auras.insert_threat_snapshot_like_cpp(slot, snapshot.clone());
                let interrupt_flags = snapshot.interrupt_flags();
                for &(effect_bit, aura_type, amount, misc_value) in snapshot.effects() {
                    let aura =
                        wow_entities::AppliedAuraRef::new(spell_id, caster_guid, slot, effect_bit);
                    auras.register_applied_aura(aura, None, interrupt_flags[0], interrupt_flags[1]);
                    auras
                        .register_applied_aura_effect_like_cpp(aura, aura_type, amount, misc_value);
                }
            });
        }
    }
    pub(in crate::session) fn hydrate_canonical_threat_relevant_auras_like_cpp(&mut self) {
        let Some(auras) = crate::session::hub_ref(self)
            .resolved_player_visible_auras_like_cpp()
            .map(|auras| auras.into_values().collect::<Vec<_>>())
        else {
            return;
        };
        for aura in auras {
            self.sync_canonical_threat_relevant_aura_like_cpp(
                aura.spell_id,
                aura.caster_guid,
                aura.slot,
                aura.effect_mask,
                &aura.represented_effect_amounts,
                true,
            );
        }
    }
    pub(in crate::session) fn represented_visibility_source_combat_reach_like_cpp(&self) -> f32 {
        let Some(player_guid) = self.player_guid() else {
            return 0.0;
        };
        let seer_guid = self
            .current_seer_guid_like_cpp()
            .filter(|guid| !guid.is_empty())
            .unwrap_or(player_guid);

        if let (Some(key), Some(manager)) = (
            self.core.current_canonical_player_map_key_like_cpp(),
            self.core.canonical_map_manager.as_ref(),
        ) && let Ok(manager) = manager.lock()
            && let Some(reach) = manager
                .find_map(key.map_id, key.instance_id)
                .and_then(|managed| {
                    managed.map().with_world_object_by_kinds_like_cpp(
                        seer_guid,
                        wow_entities::represented_seer_kinds_like_cpp(),
                        |object| object.combat_reach(),
                    )
                })
        {
            return reach.max(0.0);
        }

        self.core
            .canonical_player_combat_reach_snapshot_like_cpp()
            .max(0.0)
    }
}



#[cfg(test)]
#[path = "../../../unit_tests/session/world_entities/aggro/f3_shims.rs"]
mod f3_shims;
