use super::{LoadError, NumericRow, SqlResult};
use wow_persistence::forever::items::SparseItemRow;

pub(super) fn read(row: &SqlResult) -> Result<SparseItemRow, LoadError> {
    let mut r = NumericRow::new(row, 104)?;
    let value = SparseItemRow {
        id: r.read()?,
        strings: [r.text()?, r.text()?, r.text()?, r.text()?, r.text()?],
        expansion: r.read()?,
        damage_variance: r.read()?,
        limit_category: r.read()?,
        duration: r.read()?,
        quality_modifier: r.read()?,
        bag_family: r.read()?,
        start_quest: r.read()?,
        language: r.read()?,
        item_range: r.read()?,
        socket_percentage: r.array()?,
        stat_percent: r.array()?,
        stat_bonus: r.array()?,
        stackable: r.read()?,
        max_count: r.read()?,
        min_reputation: r.read()?,
        required_ability: r.read()?,
        allowable_race: r.array()?,
        sell_price: r.read()?,
        buy_price: r.read()?,
        vendor_stack: r.read()?,
        price_variance: r.read()?,
        price_random: r.read()?,
        flags: r.array()?,
        faction_related: r.read()?,
        modified_crafting_reagent: r.read()?,
        content_tuning: r.read()?,
        player_level_curve: r.read()?,
        item_level_offset_curve: r.read()?,
        item_level_offset: r.read()?,
        squish_era: r.read()?,
        name_description: r.read()?,
        transmog_holiday: r.read()?,
        holiday: r.read()?,
        gem_properties: r.read()?,
        socket_enchantment: r.read()?,
        totem_category: r.read()?,
        instance_bound: r.read()?,
        zone_bound: r.array()?,
        item_set: r.read()?,
        lock: r.read()?,
        page: r.read()?,
        delay: r.read()?,
        min_faction: r.read()?,
        required_skill_rank: r.read()?,
        required_skill: r.read()?,
        item_level: r.read()?,
        allowable_class: r.read()?,
        artifact: r.read()?,
        spell_weight: r.read()?,
        spell_weight_category: r.read()?,
        socket_type: r.array()?,
        sheathe: r.read()?,
        material: r.read()?,
        page_material: r.read()?,
        bonding: r.read()?,
        damage_type: r.read()?,
        container_slots: r.read()?,
        required_pvp_medal: r.read()?,
        required_pvp_rank: r.read()?,
        required_level: r.read()?,
        inventory_type: r.read()?,
        quality: r.read()?,
        ammunition: r.read()?,
    };
    r.finish()?;
    Ok(value)
}
