//! Session-key generators used during the authentication and world-session
//! handshake to derive symmetric encryption keys from the SRP6 session key.
//!
//! Two variants exist:
//! - [`SessionKeyGenerator`] uses SHA-1 (20-byte blocks).
//! - [`SessionKeyGenerator256`] uses SHA-256 (32-byte blocks).

use sha1::Sha1;
use sha2::Sha256;
use digest::Digest;

// ---------------------------------------------------------------------------
// SHA-1 variant (20-byte blocks)
// ---------------------------------------------------------------------------

/// SHA-1 based session-key generator (20-byte internal block).
pub struct SessionKeyGenerator {
    o0: [u8; 20],
    o1: [u8; 20],
    o2: [u8; 20],
    taken: usize,
}

impl SessionKeyGenerator {
    /// Create a new generator from an arbitrary-length seed.
    ///
    /// The seed is split in half; the first half seeds `o1`, the second seeds
    /// `o2`. An initial `fill_up` is performed so that bytes are immediately
    /// available via [`generate`](Self::generate).
    pub fn new(seed: &[u8]) -> Self {
        let half = seed.len() / 2;
        let first = &seed[..half];
        let second = &seed[half..];

        let o1 = sha1_hash(first);
        let o2 = sha1_hash(second);
        let o0 = [0u8; 20];

        let mut this = Self {
            o0,
            o1,
            o2,
            taken: 20, // force fill_up on first generate
        };
        this.fill_up();
        this
    }

    fn fill_up(&mut self) {
        let mut hasher = Sha1::new();
        hasher.update(self.o1);
        hasher.update(self.o0);
        hasher.update(self.o2);
        self.o0 = hasher.finalize().into();
        self.taken = 0;
    }

    /// Write generated bytes into `buf`.
    pub fn generate(&mut self, buf: &mut [u8]) {
        for b in buf.iter_mut() {
            if self.taken >= 20 {
                self.fill_up();
            }
            *b = self.o0[self.taken];
            self.taken += 1;
        }
    }
}

fn sha1_hash(data: &[u8]) -> [u8; 20] {
    let mut h = Sha1::new();
    h.update(data);
    h.finalize().into()
}

// ---------------------------------------------------------------------------
// SHA-256 variant (32-byte blocks)
// ---------------------------------------------------------------------------

/// SHA-256 based session-key generator (32-byte internal block).
pub struct SessionKeyGenerator256 {
    o0: [u8; 32],
    o1: [u8; 32],
    o2: [u8; 32],
    taken: usize,
}

impl SessionKeyGenerator256 {
    /// Create a new generator from an arbitrary-length seed.
    pub fn new(seed: &[u8]) -> Self {
        let half = seed.len() / 2;
        let first = &seed[..half];
        let second = &seed[half..];

        let o1 = sha256_hash(first);
        let o2 = sha256_hash(second);
        let o0 = [0u8; 32];

        let mut this = Self {
            o0,
            o1,
            o2,
            taken: 32,
        };
        this.fill_up();
        this
    }

    fn fill_up(&mut self) {
        let mut hasher = Sha256::new();
        hasher.update(self.o1);
        hasher.update(self.o0);
        hasher.update(self.o2);
        self.o0 = hasher.finalize().into();
        self.taken = 0;
    }

    /// Write generated bytes into `buf`.
    pub fn generate(&mut self, buf: &mut [u8]) {
        for b in buf.iter_mut() {
            if self.taken >= 32 {
                self.fill_up();
            }
            *b = self.o0[self.taken];
            self.taken += 1;
        }
    }
}

fn sha256_hash(data: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(data);
    h.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha1_deterministic() {
        let seed = b"0123456789abcdef0123456789abcdef01234567";
        let mut g1 = SessionKeyGenerator::new(seed);
        let mut g2 = SessionKeyGenerator::new(seed);

        let mut out1 = [0u8; 64];
        let mut out2 = [0u8; 64];
        g1.generate(&mut out1);
        g2.generate(&mut out2);
        assert_eq!(out1, out2);
    }

    #[test]
    fn sha1_spans_multiple_blocks() {
        let seed = b"some session key material here!!";
        let mut keygen = SessionKeyGenerator::new(seed);

        // Request more than 20 bytes to force multiple fill_up calls.
        let mut out = [0u8; 60];
        keygen.generate(&mut out);

        // The output must not be all zeros (generator is producing data).
        assert!(out.iter().any(|&b| b != 0));
    }

    #[test]
    fn sha256_deterministic() {
        let seed = b"0123456789abcdef0123456789abcdef";
        let mut g1 = SessionKeyGenerator256::new(seed);
        let mut g2 = SessionKeyGenerator256::new(seed);

        let mut out1 = [0u8; 96];
        let mut out2 = [0u8; 96];
        g1.generate(&mut out1);
        g2.generate(&mut out2);
        assert_eq!(out1, out2);
    }

    #[test]
    fn sha256_spans_multiple_blocks() {
        let seed = b"another session key for testing!";
        let mut keygen = SessionKeyGenerator256::new(seed);

        let mut out = [0u8; 100];
        keygen.generate(&mut out);
        assert!(out.iter().any(|&b| b != 0));
    }

    #[test]
    fn sha1_incremental_matches_bulk() {
        let seed = b"incremental vs bulk test seed!!!";
        let mut g1 = SessionKeyGenerator::new(seed);
        let mut g2 = SessionKeyGenerator::new(seed);

        // Bulk: generate 40 bytes at once.
        let mut bulk = [0u8; 40];
        g1.generate(&mut bulk);

        // Incremental: generate 40 bytes one at a time.
        let mut inc = [0u8; 40];
        for i in 0..40 {
            g2.generate(&mut inc[i..i + 1]);
        }

        assert_eq!(bulk, inc);
    }
}
