//! `spell_effect_types` constants, moved out of the spell module root under #646.
//!
//! Every value is unchanged.

pub const SPELL_EFFECT_NONE: u32 = 0;
pub const SPELL_EFFECT_INSTAKILL: u32 = 1;
pub const SPELL_EFFECT_SCHOOL_DAMAGE: u32 = 2;
pub const SPELL_EFFECT_DUMMY: u32 = 3;
pub const SPELL_EFFECT_PORTAL_TELEPORT: u32 = 4;
pub const SPELL_EFFECT_APPLY_AURA: u32 = 6;
pub const SPELL_EFFECT_ENVIRONMENTAL_DAMAGE: u32 = 7;
pub const SPELL_EFFECT_POWER_DRAIN: u32 = 8;
pub const SPELL_EFFECT_HEALTH_LEECH: u32 = 9;
pub const SPELL_EFFECT_HEAL: u32 = 10;
pub const SPELL_EFFECT_BIND: u32 = 11;
pub const SPELL_EFFECT_PORTAL: u32 = 12;
pub const SPELL_EFFECT_RITUAL_BASE: u32 = 13;
pub const SPELL_EFFECT_RITUAL_SPECIALIZE: u32 = 14;
pub const SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL: u32 = 15;
pub const SPELL_EFFECT_QUEST_COMPLETE: u32 = 16;
pub const SPELL_EFFECT_ADD_EXTRA_ATTACKS: u32 = 19;
pub const SPELL_EFFECT_DODGE: u32 = 20;
pub const SPELL_EFFECT_EVADE: u32 = 21;
pub const SPELL_EFFECT_PARRY: u32 = 22;
pub const SPELL_EFFECT_BLOCK: u32 = 23;
pub const SPELL_EFFECT_WEAPON: u32 = 25;
pub const SPELL_EFFECT_DEFENSE: u32 = 26;
pub const SPELL_EFFECT_PERSISTENT_AREA_AURA: u32 = 27;
pub const SPELL_EFFECT_ENERGIZE: u32 = 30;
pub const SPELL_EFFECT_APPLY_AREA_AURA_PARTY: u32 = 35;
pub const SPELL_EFFECT_LEARN_SPELL: u32 = 36;
pub const SPELL_EFFECT_SPELL_DEFENSE: u32 = 37;
pub const SPELL_EFFECT_LANGUAGE: u32 = 39;
pub const SPELL_EFFECT_DUAL_WIELD: u32 = 40;
/// C++ `SPELL_EFFECT_SKILL_STEP`; used by `SpellMgr::LoadSpellLearnSpells`
/// to mark dependent learn-spell rows as auto-learned.
pub const SPELL_EFFECT_SKILL_STEP: u32 = 44;
pub const SPELL_EFFECT_PLAY_MOVIE: u32 = 45;
pub const SPELL_EFFECT_SPAWN: u32 = 46;
pub const SPELL_EFFECT_TRADE_SKILL: u32 = 47;
pub const SPELL_EFFECT_STEALTH: u32 = 48;
pub const SPELL_EFFECT_DETECT: u32 = 49;
pub const SPELL_EFFECT_FORCE_CRITICAL_HIT: u32 = 51;
pub const SPELL_EFFECT_GUARANTEE_HIT: u32 = 52;
pub const SPELL_EFFECT_PROFICIENCY: u32 = 60;
pub const SPELL_EFFECT_POWER_BURN: u32 = 62;
pub const SPELL_EFFECT_THREAT: u32 = 63;
pub const SPELL_EFFECT_APPLY_AREA_AURA_RAID: u32 = 65;
pub const SPELL_EFFECT_HEAL_MAX_HEALTH: u32 = 67;
pub const SPELL_EFFECT_DISTRACT: u32 = 69;
pub const SPELL_EFFECT_PULL: u32 = 70;
pub const SPELL_EFFECT_ADD_FARSIGHT: u32 = 72;
pub const SPELL_EFFECT_HEAL_MECHANICAL: u32 = 75;
/// C++ `SPELL_EFFECT_SUMMON_OBJECT_WILD`; see
/// `Spell::EffectSummonObjectWild` (`SpellEffects.cpp:2937-2986`).
pub const SPELL_EFFECT_SUMMON_OBJECT_WILD: u32 = 76;
pub const SPELL_EFFECT_ATTACK: u32 = 78;
pub const SPELL_EFFECT_SANCTUARY: u32 = 79;
/// C++ `SPELL_EFFECT_ADD_COMBO_POINTS`; in the current legacy source
/// `Spell::EffectAddComboPoints` validates the hit/unit target and then
/// has its combo-point mutation commented out (`SpellEffects.cpp:3164`).
pub const SPELL_EFFECT_ADD_COMBO_POINTS: u32 = 80;
pub const SPELL_EFFECT_CREATE_HOUSE: u32 = 81;
pub const SPELL_EFFECT_BIND_SIGHT: u32 = 82;
pub const SPELL_EFFECT_DUEL: u32 = 83;
pub const SPELL_EFFECT_STUCK: u32 = 84;
pub const SPELL_EFFECT_KILL_CREDIT: u32 = 90;
pub const SPELL_EFFECT_THREAT_ALL: u32 = 91;
pub const SPELL_EFFECT_FORCE_DESELECT: u32 = 93;
pub const SPELL_EFFECT_SELF_RESURRECT: u32 = 94;
pub const SPELL_EFFECT_INEBRIATE: u32 = 100;
pub const SPELL_EFFECT_DISMISS_PET: u32 = 102;
pub const SPELL_EFFECT_REPUTATION: u32 = 103;
/// First C++ `SPELL_EFFECT_SUMMON_OBJECT_SLOT*` value; see
/// `Spell::EffectSummonObject` (`SpellEffects.cpp:3541-3597`).
pub const SPELL_EFFECT_SUMMON_OBJECT_SLOT1: u32 = 104;
pub const SPELL_EFFECT_SURVEY: u32 = 105;
pub const SPELL_EFFECT_CHANGE_RAID_MARKER: u32 = 106;
pub const SPELL_EFFECT_SHOW_CORPSE_LOOT: u32 = 107;
pub const SPELL_EFFECT_112: u32 = 112;
pub const SPELL_EFFECT_ATTACK_ME: u32 = 114;
/// C++ `SPELL_EFFECT_SKILL`; `SpellMgr::LoadSpellLearnSkills` derives
/// `mSpellLearnSkills` from this effect.
pub const SPELL_EFFECT_SKILL: u32 = 118;
pub const SPELL_EFFECT_APPLY_AREA_AURA_PET: u32 = 119;
pub const SPELL_EFFECT_122: u32 = 122;
pub const SPELL_EFFECT_MODIFY_THREAT_PERCENT: u32 = 125;
pub const SPELL_EFFECT_APPLY_AREA_AURA_FRIEND: u32 = 128;
pub const SPELL_EFFECT_APPLY_AREA_AURA_ENEMY: u32 = 129;
pub const SPELL_EFFECT_KILL_CREDIT2: u32 = 134;
pub const SPELL_EFFECT_CALL_PET: u32 = 135;
pub const SPELL_EFFECT_HEAL_PCT: u32 = 136;
pub const SPELL_EFFECT_ENERGIZE_PCT: u32 = 137;
pub const SPELL_EFFECT_APPLY_AREA_AURA_OWNER: u32 = 143;
/// C++ `SPELL_EFFECT_TITAN_GRIP`; see `Spell::EffectTitanGrip`
/// (`SpellEffects.cpp:4910-4919`).
pub const SPELL_EFFECT_TITAN_GRIP: u32 = 155;
pub const SPELL_EFFECT_OBLITERATE_ITEM: u32 = 163;
pub const SPELL_EFFECT_ALLOW_CONTROL_PET: u32 = 168;
pub const SPELL_EFFECT_APPLY_AURA_ON_PET: u32 = 174;
pub const SPELL_EFFECT_175: u32 = 175;
pub const SPELL_EFFECT_DESPAWN_PERSISTENT_AREA_AURA: u32 = 177;
pub const SPELL_EFFECT_178: u32 = 178;
pub const SPELL_EFFECT_UPDATE_AREATRIGGER: u32 = 180;
pub const SPELL_EFFECT_DESPAWN_AREATRIGGER: u32 = 182;
pub const SPELL_EFFECT_183: u32 = 183;
pub const SPELL_EFFECT_REPUTATION_2: u32 = 184;
pub const SPELL_EFFECT_185: u32 = 185;
pub const SPELL_EFFECT_186: u32 = 186;
pub const SPELL_EFFECT_RANDOMIZE_ARCHAEOLOGY_DIGSITES: u32 = 187;
pub const SPELL_EFFECT_SUMMON_STABLED_PET_AS_GUARDIAN: u32 = 188;
pub const SPELL_EFFECT_LOOT: u32 = 189;
pub const SPELL_EFFECT_CHANGE_PARTY_MEMBERS: u32 = 190;
pub const SPELL_EFFECT_TELEPORT_TO_DIGSITE: u32 = 191;
pub const SPELL_EFFECT_UNCAGE_BATTLEPET: u32 = 192;
pub const SPELL_EFFECT_START_PET_BATTLE: u32 = 193;
pub const SPELL_EFFECT_194: u32 = 194;
pub const SPELL_EFFECT_DESPAWN_SUMMON: u32 = 199;
pub const SPELL_EFFECT_APPLY_AREA_AURA_SUMMONS: u32 = 202;
pub const SPELL_EFFECT_CHANGE_BATTLEPET_QUALITY: u32 = 204;
pub const SPELL_EFFECT_ALTER_ITEM: u32 = 206;
pub const SPELL_EFFECT_LAUNCH_QUEST_TASK: u32 = 207;
pub const SPELL_EFFECT_SET_REPUTATION: u32 = 208;
pub const SPELL_EFFECT_209: u32 = 209;
pub const SPELL_EFFECT_LEARN_GARRISON_BUILDING: u32 = 210;
pub const SPELL_EFFECT_LEARN_GARRISON_SPECIALIZATION: u32 = 211;
pub const SPELL_EFFECT_CREATE_GARRISON: u32 = 214;
pub const SPELL_EFFECT_UPGRADE_CHARACTER_SPELLS: u32 = 215;
pub const SPELL_EFFECT_CREATE_SHIPMENT: u32 = 216;
pub const SPELL_EFFECT_UPGRADE_GARRISON: u32 = 217;
pub const SPELL_EFFECT_218: u32 = 218;
pub const SPELL_EFFECT_ADD_GARRISON_FOLLOWER: u32 = 220;
pub const SPELL_EFFECT_ADD_GARRISON_MISSION: u32 = 221;
pub const SPELL_EFFECT_CHANGE_ITEM_BONUSES: u32 = 223;
pub const SPELL_EFFECT_ACTIVATE_GARRISON_BUILDING: u32 = 224;
pub const SPELL_EFFECT_GRANT_BATTLEPET_LEVEL: u32 = 225;
pub const SPELL_EFFECT_TRIGGER_ACTION_SET: u32 = 226;
pub const SPELL_EFFECT_TELEPORT_TO_LFG_DUNGEON: u32 = 227;
pub const SPELL_EFFECT_228: u32 = 228;
pub const SPELL_EFFECT_SET_FOLLOWER_QUALITY: u32 = 229;
pub const SPELL_EFFECT_230: u32 = 230;
pub const SPELL_EFFECT_INCREASE_FOLLOWER_EXPERIENCE: u32 = 231;
pub const SPELL_EFFECT_REMOVE_PHASE: u32 = 232;
pub const SPELL_EFFECT_RANDOMIZE_FOLLOWER_ABILITIES: u32 = 233;
pub const SPELL_EFFECT_234: u32 = 234;
pub const SPELL_EFFECT_235: u32 = 235;
pub const SPELL_EFFECT_INCREASE_SKILL: u32 = 238;
pub const SPELL_EFFECT_END_GARRISON_BUILDING_CONSTRUCTION: u32 = 239;
pub const SPELL_EFFECT_GIVE_ARTIFACT_POWER: u32 = 240;
pub const SPELL_EFFECT_241: u32 = 241;
pub const SPELL_EFFECT_GIVE_ARTIFACT_POWER_NO_BONUS: u32 = 242;
pub const SPELL_EFFECT_LEARN_FOLLOWER_ABILITY: u32 = 244;
pub const SPELL_EFFECT_UPGRADE_HEIRLOOM: u32 = 245;
pub const SPELL_EFFECT_FINISH_GARRISON_MISSION: u32 = 246;
pub const SPELL_EFFECT_ADD_GARRISON_MISSION_SET: u32 = 247;
pub const SPELL_EFFECT_FINISH_SHIPMENT: u32 = 248;
pub const SPELL_EFFECT_FORCE_EQUIP_ITEM: u32 = 249;
pub const SPELL_EFFECT_TAKE_SCREENSHOT: u32 = 250;
pub const SPELL_EFFECT_SET_GARRISON_CACHE_SIZE: u32 = 251;
pub const SPELL_EFFECT_TELEPORT_UNITS: u32 = 252;
pub const SPELL_EFFECT_GIVE_HONOR: u32 = 253;
pub const SPELL_EFFECT_JUMP_CHARGE: u32 = 254;
pub const SPELL_EFFECT_LEARN_TRANSMOG_SET: u32 = 255;
pub const SPELL_EFFECT_256: u32 = 256;
pub const SPELL_EFFECT_257: u32 = 257;
pub const SPELL_EFFECT_MODIFY_KEYSTONE: u32 = 258;
pub const SPELL_EFFECT_RESPEC_AZERITE_EMPOWERED_ITEM: u32 = 259;
pub const SPELL_EFFECT_SUMMON_STABLED_PET: u32 = 260;
pub const SPELL_EFFECT_SCRAP_ITEM: u32 = 261;
pub const SPELL_EFFECT_262: u32 = 262;
pub const SPELL_EFFECT_REPAIR_ITEM: u32 = 263;
pub const SPELL_EFFECT_REMOVE_GEM: u32 = 264;
pub const SPELL_EFFECT_LEARN_AZERITE_ESSENCE_POWER: u32 = 265;
pub const SPELL_EFFECT_SET_ITEM_BONUS_LIST_GROUP_ENTRY: u32 = 266;
pub const SPELL_EFFECT_APPLY_MOUNT_EQUIPMENT: u32 = 268;
pub const SPELL_EFFECT_INCREASE_ITEM_BONUS_LIST_GROUP_STEP: u32 = 269;
pub const SPELL_EFFECT_270: u32 = 270;
pub const SPELL_EFFECT_APPLY_AREA_AURA_PARTY_NONRANDOM: u32 = 271;
pub const SPELL_EFFECT_SET_COVENANT: u32 = 272;
pub const SPELL_EFFECT_CRAFT_RUNEFORGE_LEGENDARY: u32 = 273;
pub const SPELL_EFFECT_274: u32 = 274;
pub const SPELL_EFFECT_275: u32 = 275;
pub const SPELL_EFFECT_LEARN_TRANSMOG_ILLUSION: u32 = 276;
pub const SPELL_EFFECT_SET_CHROMIE_TIME: u32 = 277;
pub const SPELL_EFFECT_278: u32 = 278;
pub const SPELL_EFFECT_LEARN_GARR_TALENT: u32 = 279;
pub const SPELL_EFFECT_280: u32 = 280;
pub const SPELL_EFFECT_LEARN_SOULBIND_CONDUIT: u32 = 281;
pub const SPELL_EFFECT_CONVERT_ITEMS_TO_CURRENCY: u32 = 282;
pub const SPELL_EFFECT_COMPLETE_CAMPAIGN: u32 = 283;
pub const SPELL_EFFECT_MODIFY_KEYSTONE_2: u32 = 285;
pub const SPELL_EFFECT_GRANT_BATTLEPET_EXPERIENCE: u32 = 286;
pub const SPELL_EFFECT_SET_GARRISON_FOLLOWER_LEVEL: u32 = 287;
pub const SPELL_EFFECT_CRAFT_ITEM: u32 = 288;
pub const SPELL_EFFECT_MODIFY_AURA_STACKS: u32 = 289;
pub const SPELL_EFFECT_MODIFY_COOLDOWN: u32 = 290;
pub const SPELL_EFFECT_MODIFY_COOLDOWNS: u32 = 291;
pub const SPELL_EFFECT_MODIFY_COOLDOWNS_BY_CATEGORY: u32 = 292;
pub const SPELL_EFFECT_MODIFY_CHARGES: u32 = 293;
pub const SPELL_EFFECT_CRAFT_LOOT: u32 = 294;
pub const SPELL_EFFECT_SALVAGE_ITEM: u32 = 295;
pub const SPELL_EFFECT_CRAFT_SALVAGE_ITEM: u32 = 296;
pub const SPELL_EFFECT_RECRAFT_ITEM: u32 = 297;
pub const SPELL_EFFECT_CANCEL_ALL_PRIVATE_CONVERSATIONS: u32 = 298;
pub const SPELL_EFFECT_299: u32 = 299;
pub const SPELL_EFFECT_300: u32 = 300;
pub const SPELL_EFFECT_CRAFT_ENCHANT: u32 = 301;
pub const SPELL_EFFECT_GATHERING: u32 = 302;
pub const SPELL_EFFECT_305: u32 = 305;
pub const SPELL_EFFECT_UPDATE_INTERACTIONS: u32 = 306;
pub const SPELL_EFFECT_307: u32 = 307;
pub const SPELL_EFFECT_CANCEL_PRELOAD_WORLD: u32 = 308;
pub const SPELL_EFFECT_PRELOAD_WORLD: u32 = 309;
pub const SPELL_EFFECT_310: u32 = 310;
pub const SPELL_EFFECT_ENSURE_WORLD_LOADED: u32 = 311;
pub const SPELL_EFFECT_312: u32 = 312;
pub const SPELL_EFFECT_CHANGE_ITEM_BONUSES_2: u32 = 313;
pub const SPELL_EFFECT_ADD_SOCKET_BONUS: u32 = 314;
pub const SPELL_EFFECT_LEARN_TRANSMOG_APPEARANCE_FROM_ITEM_MOD_APPEARANCE_GROUP: u32 = 315;

/// C++ dispatch entries that intentionally run as represented no-ops in
/// `SpellEffects.cpp` for the covered effect range: `EffectNULL`,
/// `EffectUnused`, or a concrete handler whose mutation is disabled in
/// this legacy source. This deliberately excludes `SPELL_EFFECT_DUMMY`,
/// whose behavior is script-driven through `ScriptMgr::OnSpellEffectDummy`.
pub fn is_cpp_null_or_unused_noop(effect: u32) -> bool {
    matches!(
        effect,
        SPELL_EFFECT_NONE
            | SPELL_EFFECT_PORTAL_TELEPORT
            | SPELL_EFFECT_PORTAL
            | SPELL_EFFECT_RITUAL_BASE
            | SPELL_EFFECT_RITUAL_SPECIALIZE
            | SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL
            | SPELL_EFFECT_DODGE
            | SPELL_EFFECT_EVADE
            | SPELL_EFFECT_WEAPON
            | SPELL_EFFECT_DEFENSE
            | SPELL_EFFECT_APPLY_AREA_AURA_PARTY
            | SPELL_EFFECT_SPELL_DEFENSE
            | SPELL_EFFECT_LANGUAGE
            | SPELL_EFFECT_SPAWN
            | SPELL_EFFECT_STEALTH
            | SPELL_EFFECT_DETECT
            | SPELL_EFFECT_FORCE_CRITICAL_HIT
            | SPELL_EFFECT_GUARANTEE_HIT
            | SPELL_EFFECT_APPLY_AREA_AURA_RAID
            | SPELL_EFFECT_ATTACK
            | SPELL_EFFECT_ADD_COMBO_POINTS
            | SPELL_EFFECT_CREATE_HOUSE
            | SPELL_EFFECT_BIND_SIGHT
            | SPELL_EFFECT_THREAT_ALL
            | SPELL_EFFECT_SURVEY
            | SPELL_EFFECT_SHOW_CORPSE_LOOT
            | SPELL_EFFECT_112
            | SPELL_EFFECT_APPLY_AREA_AURA_PET
            | SPELL_EFFECT_122
            | SPELL_EFFECT_APPLY_AREA_AURA_FRIEND
            | SPELL_EFFECT_APPLY_AREA_AURA_ENEMY
            | SPELL_EFFECT_CALL_PET
            | SPELL_EFFECT_APPLY_AREA_AURA_OWNER
            | SPELL_EFFECT_OBLITERATE_ITEM
            | SPELL_EFFECT_ALLOW_CONTROL_PET
            | SPELL_EFFECT_175
            | SPELL_EFFECT_DESPAWN_PERSISTENT_AREA_AURA
            | SPELL_EFFECT_178
            | SPELL_EFFECT_UPDATE_AREATRIGGER
            | SPELL_EFFECT_DESPAWN_AREATRIGGER
            | SPELL_EFFECT_183
            | SPELL_EFFECT_REPUTATION_2
            | SPELL_EFFECT_185
            | SPELL_EFFECT_186
            | SPELL_EFFECT_RANDOMIZE_ARCHAEOLOGY_DIGSITES
            | SPELL_EFFECT_SUMMON_STABLED_PET_AS_GUARDIAN
            | SPELL_EFFECT_LOOT
            | SPELL_EFFECT_CHANGE_PARTY_MEMBERS
            | SPELL_EFFECT_TELEPORT_TO_DIGSITE
            | SPELL_EFFECT_START_PET_BATTLE
            | SPELL_EFFECT_194
            | SPELL_EFFECT_DESPAWN_SUMMON
            | SPELL_EFFECT_APPLY_AREA_AURA_SUMMONS
            | SPELL_EFFECT_ALTER_ITEM
            | SPELL_EFFECT_LAUNCH_QUEST_TASK
            | SPELL_EFFECT_SET_REPUTATION
            | SPELL_EFFECT_209
            | SPELL_EFFECT_LEARN_GARRISON_BUILDING
            | SPELL_EFFECT_LEARN_GARRISON_SPECIALIZATION
            | SPELL_EFFECT_CREATE_GARRISON
            | SPELL_EFFECT_UPGRADE_CHARACTER_SPELLS
            | SPELL_EFFECT_CREATE_SHIPMENT
            | SPELL_EFFECT_UPGRADE_GARRISON
            | SPELL_EFFECT_218
            | SPELL_EFFECT_ADD_GARRISON_FOLLOWER
            | SPELL_EFFECT_ADD_GARRISON_MISSION
            | SPELL_EFFECT_CHANGE_ITEM_BONUSES
            | SPELL_EFFECT_ACTIVATE_GARRISON_BUILDING
            | SPELL_EFFECT_TRIGGER_ACTION_SET
            | SPELL_EFFECT_TELEPORT_TO_LFG_DUNGEON
            | SPELL_EFFECT_228
            | SPELL_EFFECT_SET_FOLLOWER_QUALITY
            | SPELL_EFFECT_230
            | SPELL_EFFECT_INCREASE_FOLLOWER_EXPERIENCE
            | SPELL_EFFECT_REMOVE_PHASE
            | SPELL_EFFECT_RANDOMIZE_FOLLOWER_ABILITIES
            | SPELL_EFFECT_234
            | SPELL_EFFECT_235
            | SPELL_EFFECT_INCREASE_SKILL
            | SPELL_EFFECT_END_GARRISON_BUILDING_CONSTRUCTION
            | SPELL_EFFECT_GIVE_ARTIFACT_POWER
            | SPELL_EFFECT_241
            | SPELL_EFFECT_GIVE_ARTIFACT_POWER_NO_BONUS
            | SPELL_EFFECT_LEARN_FOLLOWER_ABILITY
            | SPELL_EFFECT_FINISH_GARRISON_MISSION
            | SPELL_EFFECT_ADD_GARRISON_MISSION_SET
            | SPELL_EFFECT_FINISH_SHIPMENT
            | SPELL_EFFECT_FORCE_EQUIP_ITEM
            | SPELL_EFFECT_TAKE_SCREENSHOT
            | SPELL_EFFECT_SET_GARRISON_CACHE_SIZE
            | SPELL_EFFECT_256
            | SPELL_EFFECT_257
            | SPELL_EFFECT_MODIFY_KEYSTONE
            | SPELL_EFFECT_RESPEC_AZERITE_EMPOWERED_ITEM
            | SPELL_EFFECT_SUMMON_STABLED_PET
            | SPELL_EFFECT_SCRAP_ITEM
            | SPELL_EFFECT_262
            | SPELL_EFFECT_REPAIR_ITEM
            | SPELL_EFFECT_REMOVE_GEM
            | SPELL_EFFECT_LEARN_AZERITE_ESSENCE_POWER
            | SPELL_EFFECT_SET_ITEM_BONUS_LIST_GROUP_ENTRY
            | SPELL_EFFECT_APPLY_MOUNT_EQUIPMENT
            | SPELL_EFFECT_INCREASE_ITEM_BONUS_LIST_GROUP_STEP
            | SPELL_EFFECT_270
            | SPELL_EFFECT_APPLY_AREA_AURA_PARTY_NONRANDOM
            | SPELL_EFFECT_SET_COVENANT
            | SPELL_EFFECT_CRAFT_RUNEFORGE_LEGENDARY
            | SPELL_EFFECT_274
            | SPELL_EFFECT_275
            | SPELL_EFFECT_SET_CHROMIE_TIME
            | SPELL_EFFECT_278
            | SPELL_EFFECT_LEARN_GARR_TALENT
            | SPELL_EFFECT_280
            | SPELL_EFFECT_LEARN_SOULBIND_CONDUIT
            | SPELL_EFFECT_CONVERT_ITEMS_TO_CURRENCY
            | SPELL_EFFECT_COMPLETE_CAMPAIGN
            | SPELL_EFFECT_MODIFY_KEYSTONE_2
            | SPELL_EFFECT_SET_GARRISON_FOLLOWER_LEVEL
            | SPELL_EFFECT_CRAFT_ITEM
            | SPELL_EFFECT_CRAFT_LOOT
            | SPELL_EFFECT_SALVAGE_ITEM
            | SPELL_EFFECT_CRAFT_SALVAGE_ITEM
            | SPELL_EFFECT_RECRAFT_ITEM
            | SPELL_EFFECT_CANCEL_ALL_PRIVATE_CONVERSATIONS
            | SPELL_EFFECT_299
            | SPELL_EFFECT_300
            | SPELL_EFFECT_CRAFT_ENCHANT
            | SPELL_EFFECT_GATHERING
            | SPELL_EFFECT_305
            | SPELL_EFFECT_UPDATE_INTERACTIONS
            | SPELL_EFFECT_307
            | SPELL_EFFECT_CANCEL_PRELOAD_WORLD
            | SPELL_EFFECT_PRELOAD_WORLD
            | SPELL_EFFECT_310
            | SPELL_EFFECT_ENSURE_WORLD_LOADED
            | SPELL_EFFECT_312
            | SPELL_EFFECT_CHANGE_ITEM_BONUSES_2
            | SPELL_EFFECT_ADD_SOCKET_BONUS
            | SPELL_EFFECT_LEARN_TRANSMOG_APPEARANCE_FROM_ITEM_MOD_APPEARANCE_GROUP
    )
}
