//! All source-selected columns; no partial server-spell projection.
use super::{LoadError, ServerSpellEffectRow, ServerSpellRow, SqlResult, field, text};
pub(super) fn effect(row: &SqlResult) -> Result<ServerSpellEffectRow, LoadError> {
    if row.field_count() != 34 {
        return Err(LoadError::InvalidRow);
    }
    Ok(ServerSpellEffectRow {
        spell_id: field(row, 0)?,
        effect_index: field(row, 1)?,
        difficulty_id: field(row, 2)?,
        effect: field(row, 3)?,
        effect_aura: field(row, 4)?,
        effect_amplitude: field(row, 5)?,
        effect_attributes: field(row, 6)?,
        effect_aura_period: field(row, 7)?,
        effect_bonus_coefficient: field(row, 8)?,
        effect_chain_amplitude: field(row, 9)?,
        effect_chain_targets: field(row, 10)?,
        effect_item_type: field(row, 11)?,
        effect_mechanic: field(row, 12)?,
        effect_points_per_resource: field(row, 13)?,
        effect_pos_facing: field(row, 14)?,
        effect_real_points_per_level: field(row, 15)?,
        effect_trigger_spell: field(row, 16)?,
        bonus_coefficient_from_ap: field(row, 17)?,
        pvp_multiplier: field(row, 18)?,
        coefficient: field(row, 19)?,
        variance: field(row, 20)?,
        resource_coefficient: field(row, 21)?,
        group_size_base_points_coefficient: field(row, 22)?,
        effect_base_points: field(row, 23)?,
        effect_misc_value: [field(row, 24)?, field(row, 25)?],
        effect_radius_index: [field(row, 26)?, field(row, 27)?],
        effect_spell_class_mask: [
            field(row, 28)?,
            field(row, 29)?,
            field(row, 30)?,
            field(row, 31)?,
        ],
        implicit_target: [field(row, 32)?, field(row, 33)?],
    })
}

pub(super) fn spell(row: &SqlResult) -> Result<ServerSpellRow, LoadError> {
    if row.field_count() != 83 {
        return Err(LoadError::InvalidRow);
    }
    Ok(ServerSpellRow {
        id: field(row, 0)?,
        difficulty_id: field(row, 1)?,
        category_id: field(row, 2)?,
        dispel: field(row, 3)?,
        mechanic: field(row, 4)?,
        attributes: [
            field(row, 5)?,
            field(row, 6)?,
            field(row, 7)?,
            field(row, 8)?,
            field(row, 9)?,
            field(row, 10)?,
            field(row, 11)?,
            field(row, 12)?,
            field(row, 13)?,
            field(row, 14)?,
            field(row, 15)?,
            field(row, 16)?,
            field(row, 17)?,
            field(row, 18)?,
            field(row, 19)?,
            field(row, 20)?,
            field(row, 21)?,
        ],
        stances: field(row, 22)?,
        stances_not: field(row, 23)?,
        targets: field(row, 24)?,
        target_creature_type: field(row, 25)?,
        requires_spell_focus: field(row, 26)?,
        facing_caster_flags: field(row, 27)?,
        caster_aura_state: field(row, 28)?,
        target_aura_state: field(row, 29)?,
        exclude_caster_aura_state: field(row, 30)?,
        exclude_target_aura_state: field(row, 31)?,
        caster_aura_spell: field(row, 32)?,
        target_aura_spell: field(row, 33)?,
        exclude_caster_aura_spell: field(row, 34)?,
        exclude_target_aura_spell: field(row, 35)?,
        caster_aura_type: field(row, 36)?,
        target_aura_type: field(row, 37)?,
        exclude_caster_aura_type: field(row, 38)?,
        exclude_target_aura_type: field(row, 39)?,
        casting_time_index: field(row, 40)?,
        recovery_time: field(row, 41)?,
        category_recovery_time: field(row, 42)?,
        start_recovery_category: field(row, 43)?,
        start_recovery_time: field(row, 44)?,
        interrupt_flags: field(row, 45)?,
        aura_interrupt_flags: [field(row, 46)?, field(row, 47)?],
        channel_interrupt_flags: [field(row, 48)?, field(row, 49)?],
        proc_flags: [field(row, 50)?, field(row, 51)?],
        proc_chance: field(row, 52)?,
        proc_charges: field(row, 53)?,
        proc_cooldown: field(row, 54)?,
        proc_base_ppm: field(row, 55)?,
        max_level: field(row, 56)?,
        base_level: field(row, 57)?,
        spell_level: field(row, 58)?,
        duration_index: field(row, 59)?,
        range_index: field(row, 60)?,
        speed: field(row, 61)?,
        launch_delay: field(row, 62)?,
        stack_amount: field(row, 63)?,
        equipped_item_class: field(row, 64)?,
        equipped_item_sub_class_mask: field(row, 65)?,
        equipped_item_inventory_type_mask: field(row, 66)?,
        content_tuning_id: field(row, 67)?,
        spell_name: text(row, 68)?,
        cone_angle: field(row, 69)?,
        cone_width: field(row, 70)?,
        max_target_level: field(row, 71)?,
        max_affected_targets: field(row, 72)?,
        spell_family_name: field(row, 73)?,
        spell_family_flags: [
            field(row, 74)?,
            field(row, 75)?,
            field(row, 76)?,
            field(row, 77)?,
        ],
        dmg_class: field(row, 78)?,
        prevention_type: field(row, 79)?,
        area_group_id: field(row, 80)?,
        school_mask: field(row, 81)?,
        charge_category_id: field(row, 82)?,
    })
}
