[package]
name = "wow-world-spell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-fixtures = [
    "wow-spell-acquisition/test-fixtures",
    "wow-world-core/test-fixtures",
]

[dependencies]
num-traits = { workspace = true }
tracing = { workspace = true }
wow-constants = { workspace = true }
wow-combat = { workspace = true }
wow-core = { workspace = true }
wow-data = { workspace = true }
wow-entities = { workspace = true }
wow-packet = { workspace = true }
wow-map = { workspace = true }
wow-spell-acquisition = { workspace = true }
wow-world-core = { workspace = true }

[dev-dependencies]
wow-spell-acquisition = { workspace = true, features = ["test-fixtures"] }
wow-world-core = { workspace = true, features = ["test-fixtures"] }

[lints]
workspace = true
