//! Full 02245dcd custom-attribute dependency fields; widths follow DB2LoadInfo.
//! Source C++ unsigned aliases of signed metadata keep their raw bit pattern.

pub struct UnitConditionRow {
    pub id: u32,
    pub flags: i32,
    pub variable: [u8; 8],
    pub op: [u8; 8],
    pub value: [i32; 8],
}

pub struct TalentRow {
    pub id: u32,
    pub description: Vec<u8>,
    pub tier_id: u8,
    pub flags: i32,
    pub column_index: u8,
    pub tab_id: u16,
    pub class_id: i8,
    pub spec_id: u16,
    pub spell_id: u32,
    pub overrides_spell_id: u32,
    pub required_spell_id: u32,
    pub category_mask: [i32; 2],
    pub spell_rank: [u32; 9],
    pub prereq_talent: [u32; 3],
    pub prereq_rank: [u8; 3],
}

/// Twelve source SQL columns are unsigned despite signed DB2 metadata.
/// Preserve the SQL width here; composition retains their raw bits as i32.
pub struct SpellItemEnchantmentRow {
    pub id: u32,
    pub name: Vec<u8>,
    pub horde_name: Vec<u8>,
    pub duration: i32,
    pub charges: u32,
    pub effect: [u32; 3],
    pub effect_points_min: [i32; 3],
    pub effect_arg: [u32; 3],
    pub flags: i32,
    pub effect_scaling_points: [f32; 3],
    pub scaling_class: i32,
    pub scaling_class_restricted: i32,
    pub condition_id: u32,
    pub required_skill_id: u32,
    pub required_skill_rank: u32,
    pub min_level: u32,
    pub max_level: u32,
    pub icon_file_data_id: u32,
    pub min_item_level: i32,
    pub max_item_level: i32,
    pub transmog_use_condition_id: u32,
    pub transmog_cost: u32,
    pub field_12_1_5_69594_021: i32,
    pub item_visual: u16,
    pub item_level: u16,
}

pub struct SpellVisualRow {
    pub id: u32,
    pub missile_cast_offset: [f32; 3],
    pub missile_impact_offset: [f32; 3],
    pub state_kit: i32,
    pub anim_event_sound_id: u32,
    pub flags: i32,
    pub missile_attachment: i8,
    pub missile_destination_attachment: i8,
    pub missile_cast_positioner_id: u32,
    pub missile_impact_positioner_id: u32,
    pub missile_targeting_kit: i32,
    pub hostile_spell_visual_id: u32,
    pub caster_spell_visual_id: u32,
    pub spell_visual_missile_set_id: u16,
    pub damage_number_delay: u16,
    pub low_violence_spell_visual_id: u32,
    pub raid_spell_visual_missile_set_id: u32,
    pub reduced_unexpected_camera_movement_spell_visual_id: i32,
}

pub struct SpellVisualMissileRow {
    pub cast_offset: [f32; 3],
    pub impact_offset: [f32; 3],
    pub id: u32,
    pub spell_visual_effect_name_id: u16,
    pub sound_entries_id: u32,
    pub attachment: i8,
    pub destination_attachment: i8,
    pub cast_positioner_id: u16,
    pub impact_positioner_id: u16,
    pub follow_ground_height: i32,
    pub follow_ground_drop_speed: u32,
    pub follow_ground_approach: u16,
    pub flags: i32,
    pub spell_missile_motion_id: u16,
    pub anim_kit_id: u32,
    pub clutter_level: i32,
    pub decay_time_after_impact: i32,
    pub unused1100: u16,
    pub field_12_1_5_69594_018: i32,
    pub field_12_1_5_69594_019: i32,
    pub field_12_1_5_69594_020: i32,
    pub field_12_1_5_69594_021: i32,
    pub spell_visual_missile_set_id: u32,
}

pub struct SpellVisualEffectNameRow {
    pub id: u32,
    pub model_file_data_id: i32,
    pub base_missile_speed: f32,
    pub scale: f32,
    pub min_allowed_scale: f32,
    pub max_allowed_scale: f32,
    pub alpha: f32,
    pub flags: i32,
    pub texture_file_data_id: i32,
    pub effect_radius: f32,
    pub r#type: i32,
    pub generic_id: i32,
    pub ribbon_quality_id: u32,
    pub dissolve_effect_id: i32,
    pub model_position: i32,
    pub unknown901: i8,
    pub unknown1100: u16,
}

pub struct LiquidTypeRow {
    pub id: u32,
    pub name: Vec<u8>,
    pub texture: [Vec<u8>; 6],
    pub flags: i32,
    pub sound_bank: u8,
    pub sound_id: u32,
    pub spell_id: u32,
    pub max_darken_depth: f32,
    pub fog_darken_intensity: f32,
    pub amb_darken_intensity: f32,
    pub dir_darken_intensity: f32,
    pub light_id: u16,
    pub particle_scale: f32,
    pub particle_movement: u8,
    pub particle_tex_slots: u8,
    pub material_id: u8,
    pub minimap_static_col: i32,
    pub frame_count_texture: [u8; 6],
    pub color: [i32; 3],
    pub float_values: [f32; 38],
    pub int_values: [u32; 4],
    pub coefficient: [f32; 4],
}
