// Copyright (c) 2026 alseif0x
// Licensed under GPL v3 — https://www.gnu.org/licenses/gpl-3.0.html

//! Quest status and objective constants from the target `Quests/QuestDef.h`.
//! Shared by catalog adapters and Player rules; no runtime or catalog dependency.

pub const QUEST_STATUS_NONE_LIKE_CPP: u8 = 0;
pub const QUEST_STATUS_COMPLETE_LIKE_CPP: u8 = 1;
pub const QUEST_STATUS_INCOMPLETE_LIKE_CPP: u8 = 3;
pub const QUEST_STATUS_FAILED_LIKE_CPP: u8 = 5;
pub const QUEST_STATUS_REWARDED_LIKE_CPP: u8 = 6;
pub const QUEST_FLAGS_EX_REWARDS_IGNORE_CAPS_LIKE_CPP: u32 = 0x0080_0000;
pub const QUEST_FLAGS_EX_IS_WORLD_QUEST_LIKE_CPP: u32 = 0x0100_0000;

pub const QUEST_FLAGS_COMPLETION_EVENT_LIKE_CPP: u32 = 0x0000_0002;
pub const QUEST_FLAGS_COMPLETION_AREA_TRIGGER_LIKE_CPP: u32 = 0x0000_0004;

pub const QUEST_OBJECTIVE_MONSTER_LIKE_CPP: u8 = 0;
pub const QUEST_OBJECTIVE_ITEM_LIKE_CPP: u8 = 1;
pub const QUEST_OBJECTIVE_GAMEOBJECT_LIKE_CPP: u8 = 2;
pub const QUEST_OBJECTIVE_TALKTO_LIKE_CPP: u8 = 3;
pub const QUEST_OBJECTIVE_PLAYERKILLS_LIKE_CPP: u8 = 9;
pub const QUEST_OBJECTIVE_WINPVPPETBATTLES_LIKE_CPP: u8 = 13;
pub const QUEST_OBJECTIVE_CRITERIA_TREE_LIKE_CPP: u8 = 14;
pub const QUEST_OBJECTIVE_PROGRESS_BAR_LIKE_CPP: u8 = 15;
pub const QUEST_OBJECTIVE_HAVE_CURRENCY_LIKE_CPP: u8 = 16;
pub const QUEST_OBJECTIVE_OBTAIN_CURRENCY_LIKE_CPP: u8 = 17;
pub const QUEST_OBJECTIVE_INCREASE_REPUTATION_LIKE_CPP: u8 = 18;
pub const QUEST_OBJECTIVE_FLAG_SEQUENCED_LIKE_CPP: u32 = 0x2;
pub const QUEST_OBJECTIVE_FLAG_OPTIONAL_LIKE_CPP: u32 = 0x4;
pub const QUEST_OBJECTIVE_FLAG_PART_OF_PROGRESS_BAR_LIKE_CPP: u32 = 0x40;
pub const QUEST_OBJECTIVE_FLAG_2_QUEST_BOUND_ITEM_LIKE_CPP: u32 = 0x1;
