#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

if [[ -f .env.local ]]; then
  set -a
  . ./.env.local
  set +a
fi

password_env_name() {
  local account="$1"
  local suffix=""
  local i ch
  for ((i = 0; i < ${#account}; i++)); do
    ch="${account:i:1}"
    if [[ "$ch" =~ [[:alnum:]] ]]; then
      suffix+="${ch^^}"
    else
      suffix+="_"
    fi
  done
  printf 'WOW_BOT_PASSWORD_%s' "$suffix"
}

ensure_local_password() {
  local account="${WOW_BOT_ACCOUNT:-TESTBOT1@bot.local}"
  local per_account_var
  per_account_var="$(password_env_name "$account")"
  if [[ -n "${WOW_BOT_PASSWORD:-}" || -n "${!per_account_var:-}" ]]; then
    return
  fi
  if [[ "${WOW_BOT_GENERATE_LOCAL_PASSWORD:-1}" =~ ^(0|false|FALSE|no|NO|off|OFF)$ ]]; then
    return
  fi

  local generated
  generated="$(openssl rand -hex 24)"
  umask 077
  if [[ ! -f .env.local ]]; then
    : >.env.local
  fi
  {
    printf '\n# Generated by run_rustycore_login_smoke.sh for local QA only.\n'
    printf 'WOW_BOT_PASSWORD=%q\n' "$generated"
  } >>.env.local
  export WOW_BOT_PASSWORD="$generated"
  echo "Generated local bot password in ignored tools/wow-test-bot/.env.local"
}

ensure_local_password

account="${WOW_BOT_ACCOUNT:-TESTBOT1@bot.local}"
timeout_secs="${WOW_BOT_LOGIN_TIMEOUT_SECS:-1}"
report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-login-only-report.json}"
log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-login-only.log}"
quest_timeout_secs="${WOW_BOT_QUEST_TIMEOUT_SECS:-5}"
ensure_accounts="${WOW_BOT_ENSURE_TEST_ACCOUNTS:-1}"

export BNET_HOST="${BNET_HOST:-127.0.0.1}"
export BNET_PORT="${BNET_PORT:-8081}"
export WORLD_HOST="${WORLD_HOST:-127.0.0.1}"
export WORLD_PORT="${WORLD_PORT:-8085}"
export INSTANCE_HOST="${INSTANCE_HOST:-127.0.0.1}"
export REALM_ID="${REALM_ID:-1}"
export WOW_BOT_CLIENT_BUILD="${WOW_BOT_CLIENT_BUILD:-${WOW_BOT_BUILD:-54261}}"
export WOW_BOT_DB_CONF="${WOW_BOT_DB_CONF:-/home/server/trinity-legacy-install/etc/worldserver.conf}"

mode_args=(--login-only --timeout "$timeout_secs")
if [[ "${WOW_BOT_QUEST_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  : "${WOW_BOT_QUEST_CREATURE_ENTRY:?Set WOW_BOT_QUEST_CREATURE_ENTRY for quest-smoke mode}"
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-quest-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-quest-smoke.log}"
  mode_args=(--quest-smoke --quest-creature-entry "$WOW_BOT_QUEST_CREATURE_ENTRY" --quest-timeout "$quest_timeout_secs")
  if [[ -n "${WOW_BOT_QUEST_CREATURE_GUID:-}" ]]; then
    mode_args+=(--quest-creature-guid "$WOW_BOT_QUEST_CREATURE_GUID")
  fi
  if [[ -n "${WOW_BOT_QUEST_GUID_COUNTER:-}" ]]; then
    mode_args+=(--quest-guid-counter "$WOW_BOT_QUEST_GUID_COUNTER")
  fi
  if [[ -n "${WOW_BOT_QUEST_MAP_ID:-}" ]]; then
    mode_args+=(--quest-map "$WOW_BOT_QUEST_MAP_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_EXPECT_ID:-}" ]]; then
    mode_args+=(--expect-quest "$WOW_BOT_QUEST_EXPECT_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_FORBID_ID:-}" ]]; then
    mode_args+=(--forbid-quest "$WOW_BOT_QUEST_FORBID_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_FORBID_TITLE_CONTAINS:-}" ]]; then
    mode_args+=(--forbid-title "$WOW_BOT_QUEST_FORBID_TITLE_CONTAINS")
  fi
  if [[ "${WOW_BOT_QUEST_QUERY_DETAILS:-1}" =~ ^(0|false|FALSE|no|NO|off|OFF)$ ]]; then
    mode_args+=(--no-quest-query-details)
  fi
  if [[ "${WOW_BOT_QUEST_ACCEPT:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-accept)
  fi
  if [[ "${WOW_BOT_QUEST_RESET:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-reset)
  fi
  if [[ "${WOW_BOT_QUEST_RELOCATE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-relocate)
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_LEVEL:-}" ]]; then
    mode_args+=(--quest-set-level "$WOW_BOT_QUEST_SET_LEVEL")
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_RACE:-}" ]]; then
    mode_args+=(--quest-set-race "$WOW_BOT_QUEST_SET_RACE")
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_CLASS:-}" ]]; then
    mode_args+=(--quest-set-class "$WOW_BOT_QUEST_SET_CLASS")
  fi
  if [[ "${WOW_BOT_QUEST_OBJECTIVE_PERSIST:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    : "${WOW_BOT_QUEST_OBJECTIVES:?Set WOW_BOT_QUEST_OBJECTIVES for quest objective persistence QA}"
    mode_args+=(--quest-objective-persist --quest-objectives "$WOW_BOT_QUEST_OBJECTIVES")
  fi
  if [[ -n "${WOW_BOT_QUEST_OBJECTIVE_STATUS:-}" ]]; then
    mode_args+=(--quest-objective-status "$WOW_BOT_QUEST_OBJECTIVE_STATUS")
  fi
fi

cargo build --bin wow-test-bot

ensure_args=()
if [[ "$ensure_accounts" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  ensure_args+=(--ensure-test-accounts)
fi

./target/debug/wow-test-bot \
  --config "${WOW_BOT_CONFIG:-config.example.json}" \
  --single "$account" \
  "${mode_args[@]}" \
  "${ensure_args[@]}" \
  --no-cleanup-groups \
  --no-auto-teleport \
  --report "$report_path" \
  >"$log_path" 2>&1

echo "RustyCore smoke passed for $account"
echo "log: $log_path"
echo "report: $report_path"

if command -v jq >/dev/null 2>&1; then
  jq '{login_only, quest_smoke, results: [.results[] | {account, world_auth, enum_characters, player_login_verified, quest_smoke_passed, quest_target_entry, quest_target_spawn_guid, quest_target_guid_counter, quest_ids_seen, quest_titles_seen, quest_accept_sent, quest_accept_confirm_seen, quest_db_verified, quest_db_status, quest_failure, join_result}]}' "$report_path"
fi
