#!/usr/bin/env bash
set -euo pipefail

# The ignored defaults file is data owned by the local operator. Keep xtrace
# off while snapshotting/restoring exported values so neither caller secrets
# nor values from that file can be echoed accidentally.
RC_CALLER_XTRACE=0
if [[ "$-" == *x* ]]; then
  RC_CALLER_XTRACE=1
  set +x
fi
readonly RC_CALLER_XTRACE

cd "$(dirname "$0")"

# Local defaults must never replace values explicitly pinned by the caller.
# This is especially important for runtime QA provenance (`WOW_BOT_EXEC*`) and
# for the selected destructive mode. Preserve every exported bot/runtime input,
# source the ignored defaults, then restore the caller-owned values verbatim.
declare -A caller_runtime_env=()
while IFS='=' read -r -d '' env_name env_value; do
  case "$env_name" in
    WOW_BOT_* | BNET_HOST | BNET_PORT | WORLD_HOST | WORLD_PORT | INSTANCE_HOST | INSTANCE_PORT | REALM_ID)
      caller_runtime_env["$env_name"]="$env_value"
      ;;
  esac
done < <(env -0)
readonly -A caller_runtime_env

RC_ENV_FILE="${WOW_BOT_ENV_FILE:-.env.local}"
readonly RC_ENV_FILE
RC_ENV_STATUS=0
if [[ -f "$RC_ENV_FILE" ]]; then
  set +e
  set -a
  . "$RC_ENV_FILE" 2>/dev/null
  RC_ENV_STATUS=$?
  set +a
  set -e
  set +x
fi
if ((RC_ENV_STATUS != 0)); then
  echo "Failed to load WOW_BOT_ENV_FILE" >&2
  exit 2
fi
for env_name in "${!caller_runtime_env[@]}"; do
  export "$env_name=${caller_runtime_env[$env_name]}"
done
unset env_name env_value
# Keep xtrace disabled while credentials and caller-owned runtime values are
# inspected. It is restored only after the complete argv has been assembled;
# the bot password is inherited through the environment, never argv.

password_env_name() {
  local account="$1"
  local suffix=""
  local i ch
  for ((i = 0; i < ${#account}; i++)); do
    ch="${account:i:1}"
    if [[ "$ch" =~ [[:alnum:]] ]]; then
      suffix+="${ch^^}"
    else
      suffix+="_"
    fi
  done
  printf 'WOW_BOT_PASSWORD_%s' "$suffix"
}

ensure_local_password() {
  local account="${WOW_BOT_ACCOUNT:-TESTBOT1@bot.local}"
  if [[ "${WOW_BOT_DETOUR_CHASE_CAPTURE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    # The deterministic capture pins TESTBOT2 and must use an explicit
    # caller-owned credential; never persist a generated shared password.
    return
  fi
  local per_account_var
  per_account_var="$(password_env_name "$account")"
  if [[ -n "${WOW_BOT_PASSWORD:-}" || -n "${!per_account_var:-}" ]]; then
    return
  fi
  if [[ "${WOW_BOT_GENERATE_LOCAL_PASSWORD:-1}" =~ ^(0|false|FALSE|no|NO|off|OFF)$ ]]; then
    return
  fi

  local generated
  generated="$(openssl rand -hex 24)"
  umask 077
  if [[ ! -f .env.local ]]; then
    : >.env.local
  fi
  {
    printf '\n# Generated by run_rustycore_login_smoke.sh for local QA only.\n'
    printf 'WOW_BOT_PASSWORD=%q\n' "$generated"
  } >>.env.local
  export WOW_BOT_PASSWORD="$generated"
  echo "Generated local bot password in ignored tools/wow-test-bot/.env.local"
}

ensure_local_password

account="${WOW_BOT_ACCOUNT:-TESTBOT1@bot.local}"
timeout_secs="${WOW_BOT_LOGIN_TIMEOUT_SECS:-1}"
report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-login-only-report.json}"
log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-login-only.log}"
quest_timeout_secs="${WOW_BOT_QUEST_TIMEOUT_SECS:-5}"
stand_state_timeout_secs="${WOW_BOT_STAND_STATE_TIMEOUT_SECS:-5}"
bank_timeout_secs="${WOW_BOT_BANK_TIMEOUT_SECS:-8}"
void_storage_timeout_secs="${WOW_BOT_VOID_STORAGE_TIMEOUT_SECS:-8}"
homebind_timeout_secs="${WOW_BOT_HOMEBIND_TIMEOUT_SECS:-8}"
inventory_swap_timeout_secs="${WOW_BOT_INVENTORY_SWAP_TIMEOUT_SECS:-8}"
vendor_timeout_secs="${WOW_BOT_VENDOR_TIMEOUT_SECS:-8}"
rested_xp_timeout_secs="${WOW_BOT_RESTED_XP_TIMEOUT_SECS:-120}"
rested_xp_offline_secs="${WOW_BOT_RESTED_XP_OFFLINE_SECS:-86400}"
detour_chase_timeout_secs="${WOW_BOT_DETOUR_CHASE_TIMEOUT_SECS:-30}"
loot_race_timeout_secs="${WOW_BOT_LOOT_RACE_TIMEOUT_SECS:-30}"
ensure_accounts="${WOW_BOT_ENSURE_TEST_ACCOUNTS:-1}"

export BNET_HOST="${BNET_HOST:-127.0.0.1}"
export BNET_PORT="${BNET_PORT:-8081}"
export WORLD_HOST="${WORLD_HOST:-127.0.0.1}"
export WORLD_PORT="${WORLD_PORT:-8085}"
export INSTANCE_HOST="${INSTANCE_HOST:-127.0.0.1}"
export REALM_ID="${REALM_ID:-1}"
export WOW_BOT_CLIENT_BUILD="${WOW_BOT_CLIENT_BUILD:-${WOW_BOT_BUILD:-54261}}"
export WOW_BOT_DB_CONF="${WOW_BOT_DB_CONF:-/home/server/trinity-legacy-install/etc/worldserver.conf}"

mode_args=(--login-only --timeout "$timeout_secs")
stand_state_requested=0
if [[ "${WOW_BOT_STAND_STATE_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ || -n "${WOW_BOT_STAND_STATE:-}" ]]; then
  stand_state_requested=1
fi
quest_requested=0
if [[ "${WOW_BOT_QUEST_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  quest_requested=1
fi
bank_requested=0
if [[ "${WOW_BOT_BANK_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  bank_requested=1
fi
void_storage_requested=0
if [[ "${WOW_BOT_VOID_STORAGE_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  void_storage_requested=1
fi
void_storage_query_capture_requested=0
if [[ "${WOW_BOT_VOID_STORAGE_QUERY_CAPTURE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  void_storage_query_capture_requested=1
fi
homebind_requested=0
if [[ "${WOW_BOT_HOMEBIND_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  homebind_requested=1
fi
inventory_swap_requested=0
if [[ "${WOW_BOT_INVENTORY_SWAP_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  inventory_swap_requested=1
fi
vendor_requested=0
if [[ "${WOW_BOT_VENDOR_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  vendor_requested=1
fi
rested_xp_requested=0
if [[ "${WOW_BOT_RESTED_XP_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  rested_xp_requested=1
fi
rested_xp_acknowledged=0
if [[ "${WOW_BOT_ACK_DISPOSABLE_RESTED_XP:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  rested_xp_acknowledged=1
fi
detour_chase_requested=0
if [[ "${WOW_BOT_DETOUR_CHASE_CAPTURE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  detour_chase_requested=1
fi
detour_chase_acknowledged=0
if [[ "${WOW_BOT_ACK_DISPOSABLE_DETOUR_FIXTURE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  detour_chase_acknowledged=1
fi
loot_race_requested=0
if [[ "${WOW_BOT_LOOT_RACE_SMOKE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  loot_race_requested=1
fi
loot_item_capture_requested=0
if [[ "${WOW_BOT_LOOT_ITEM_CAPTURE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  loot_item_capture_requested=1
fi
loot_race_acknowledged=0
if [[ "${WOW_BOT_ACK_DISPOSABLE_OVERWORLD_LOOT_RACE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  loot_race_acknowledged=1
fi
if ((rested_xp_acknowledged && !rested_xp_requested)); then
  echo "WOW_BOT_ACK_DISPOSABLE_RESTED_XP is only valid with WOW_BOT_RESTED_XP_SMOKE" >&2
  exit 2
fi
if ((detour_chase_acknowledged && !detour_chase_requested)); then
  echo "WOW_BOT_ACK_DISPOSABLE_DETOUR_FIXTURE is only valid with WOW_BOT_DETOUR_CHASE_CAPTURE" >&2
  exit 2
fi
if ((loot_race_acknowledged && !loot_race_requested && !loot_item_capture_requested)); then
  echo "WOW_BOT_ACK_DISPOSABLE_OVERWORLD_LOOT_RACE is only valid with WOW_BOT_LOOT_RACE_SMOKE or WOW_BOT_LOOT_ITEM_CAPTURE" >&2
  exit 2
fi
if ((stand_state_requested + quest_requested + bank_requested + void_storage_requested + void_storage_query_capture_requested + homebind_requested + inventory_swap_requested + vendor_requested + rested_xp_requested + detour_chase_requested + loot_race_requested + loot_item_capture_requested > 1)); then
  echo "Stand-state, quest, bank, void-storage, void-storage-query-capture, homebind, inventory-swap, vendor, rested-XP, detour-chase-capture, loot-race, and loot-item-capture are separate modes" >&2
  exit 2
fi
if ((loot_race_requested || loot_item_capture_requested)) \
    && ((!loot_race_acknowledged)); then
  echo "Loot fixture modes require WOW_BOT_ACK_DISPOSABLE_OVERWORLD_LOOT_RACE=1" >&2
  exit 2
fi

if ((detour_chase_requested)); then
  if ((!detour_chase_acknowledged)); then
    echo "Detour-chase capture requires WOW_BOT_ACK_DISPOSABLE_DETOUR_FIXTURE=1" >&2
    exit 2
  fi
  # The fixture is pre-provisioned. The Rust bot performs a read-only identity,
  # position, spawn, and asset preflight before login; generic provisioning is
  # deliberately disabled for this destructive QA mode.
  ensure_accounts=0
  export WOW_BOT_ENSURE_TEST_ACCOUNTS=0
fi

if ((loot_race_requested || loot_item_capture_requested)); then
  # Loot fixtures require pre-provisioned, already-owned disposable identities.
  # Never let the generic local bootstrap overwrite an existing numeric account
  # id or reassign a configured character before the fixture contract validates.
  ensure_accounts=0
  export WOW_BOT_ENSURE_TEST_ACCOUNTS=0
  fixture_journal="${WOW_BOT_FIXTURE_JOURNAL:-}"
  if [[ -z "$fixture_journal" || "$fixture_journal" != /* \
      || "$fixture_journal" == *$'\n'* ]]; then
    echo "Loot fixture modes require an absolute WOW_BOT_FIXTURE_JOURNAL path" >&2
    exit 2
  fi
  if [[ ! -d "$(dirname -- "$fixture_journal")" ]]; then
    echo "WOW_BOT_FIXTURE_JOURNAL parent directory does not exist" >&2
    exit 2
  fi
  fixture_cleanup_marker="${fixture_journal}.cleanup-complete"
  if [[ -e "$fixture_journal" || -L "$fixture_journal" \
      || -e "$fixture_cleanup_marker" || -L "$fixture_cleanup_marker" ]]; then
    echo "Fixture journal/cleanup marker already exists; recover or remove it explicitly before running" >&2
    exit 2
  fi
  export WOW_BOT_FIXTURE_JOURNAL="$fixture_journal"
  export WOW_BOT_REQUIRE_PARENT_DEATH_GUARD=1
fi

if ((detour_chase_requested)); then
  account="TESTBOT2@bot.local"
  detour_fixture_manifest="${WOW_BOT_DETOUR_FIXTURE_MANIFEST:-../../crates/capture-diff/flows/detour-chase-around-obstacle/fixture/fixture.json}"
  if [[ -z "$detour_fixture_manifest" ]]; then
    echo "Detour-chase capture requires WOW_BOT_DETOUR_FIXTURE_MANIFEST" >&2
    exit 2
  fi
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-detour-chase-capture-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-detour-chase-capture.log}"
  mode_args=(
    --detour-chase-capture
    --ack-disposable-detour-fixture
    --detour-fixture-manifest "$detour_fixture_manifest"
    --detour-chase-timeout "$detour_chase_timeout_secs"
  )
elif ((loot_item_capture_requested)); then
  if ((!loot_race_acknowledged)); then
    echo "Loot-item capture kills an exact overworld fixture and requires WOW_BOT_ACK_DISPOSABLE_OVERWORLD_LOOT_RACE=1" >&2
    exit 2
  fi
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-loot-item-capture-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-loot-item-capture.log}"
  mode_args=(
    --loot-item-capture
    --ack-disposable-overworld-loot-race
    --loot-race-account-a "TESTBOT2@bot.local"
    --loot-race-account-b "TESTBOT3@bot.local"
    --loot-race-creature-entry "21779"
    --loot-race-creature-spawn-guid "1117"
    --loot-race-runtime-counter "0"
    --loot-race-item-entry "30712"
    --loot-race-timeout "$loot_race_timeout_secs"
  )
elif ((loot_race_requested)); then
  if ((!loot_race_acknowledged)); then
    echo "Loot-race smoke mutates an exact shared-chest fixture and requires WOW_BOT_ACK_DISPOSABLE_OVERWORLD_LOOT_RACE=1" >&2
    exit 2
  fi
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-loot-race-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-loot-race-smoke.log}"
  mode_args=(
    --loot-race-smoke
    --ack-disposable-overworld-loot-race
    --loot-race-account-a "TESTBOT2@bot.local"
    --loot-race-account-b "TESTBOT3@bot.local"
    --loot-race-gameobject-entry "2846"
    --loot-race-gameobject-spawn-guid "9106001"
    --loot-race-runtime-counter "0"
    --loot-race-item-entry "38"
    --loot-race-timeout "$loot_race_timeout_secs"
  )
elif ((rested_xp_requested)); then
  if ((!rested_xp_acknowledged)); then
    echo "Rested-XP smoke is destructive and requires WOW_BOT_ACK_DISPOSABLE_RESTED_XP=1" >&2
    exit 2
  fi
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-rested-xp-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-rested-xp-smoke.log}"
  mode_args=(
    --rested-xp-smoke
    --ack-disposable-rested-xp
    --rested-xp-creature-entry "${WOW_BOT_RESTED_XP_CREATURE_ENTRY:-15274}"
    --rested-xp-offline-secs "$rested_xp_offline_secs"
    --rested-xp-timeout "$rested_xp_timeout_secs"
  )
  if [[ -n "${WOW_BOT_RESTED_XP_CREATURE_GUID:-}" ]]; then
    mode_args+=(--rested-xp-creature-guid "$WOW_BOT_RESTED_XP_CREATURE_GUID")
  fi
  if [[ -n "${WOW_BOT_RESTED_XP_RUNTIME_COUNTER:-}" ]]; then
    mode_args+=(--rested-xp-runtime-counter "$WOW_BOT_RESTED_XP_RUNTIME_COUNTER")
  fi
elif ((stand_state_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-stand-state-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-stand-state.log}"
  mode_args=(--stand-state-smoke --stand-state-timeout "$stand_state_timeout_secs")
  if [[ -n "${WOW_BOT_STAND_STATE:-}" ]]; then
    mode_args=(--stand-state "$WOW_BOT_STAND_STATE" --stand-state-timeout "$stand_state_timeout_secs")
  fi
elif ((bank_requested)); then
  : "${WOW_BOT_BANK_RUNTIME_COUNTER:?Set WOW_BOT_BANK_RUNTIME_COUNTER for the live banker ObjectGuid}"
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-bank-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-bank-smoke.log}"
  mode_args=(--bank-smoke --bank-runtime-counter "$WOW_BOT_BANK_RUNTIME_COUNTER" --bank-timeout "$bank_timeout_secs")
  if [[ -n "${WOW_BOT_BANK_ITEM_ENTRY:-}" ]]; then
    mode_args+=(--bank-item-entry "$WOW_BOT_BANK_ITEM_ENTRY")
  fi
elif ((void_storage_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-void-storage-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-void-storage-smoke.log}"
  mode_args=(--void-storage-smoke --void-storage-timeout "$void_storage_timeout_secs")
  if [[ -n "${WOW_BOT_VOID_STORAGE_RUNTIME_COUNTER:-}" ]]; then
    mode_args+=(--void-storage-runtime-counter "$WOW_BOT_VOID_STORAGE_RUNTIME_COUNTER")
  fi
  if [[ -n "${WOW_BOT_VOID_STORAGE_ITEM_ENTRY:-}" ]]; then
    mode_args+=(--void-storage-item-entry "$WOW_BOT_VOID_STORAGE_ITEM_ENTRY")
  fi
elif ((void_storage_query_capture_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-void-storage-query-capture-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-void-storage-query-capture.log}"
  mode_args=(--void-storage-query-capture --void-storage-timeout "$void_storage_timeout_secs")
  if [[ -n "${WOW_BOT_VOID_STORAGE_RUNTIME_COUNTER:-}" ]]; then
    mode_args+=(--void-storage-runtime-counter "$WOW_BOT_VOID_STORAGE_RUNTIME_COUNTER")
  fi
  if [[ -n "${WOW_BOT_VOID_STORAGE_ITEM_ENTRY:-}" ]]; then
    mode_args+=(--void-storage-item-entry "$WOW_BOT_VOID_STORAGE_ITEM_ENTRY")
  fi
elif ((homebind_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-homebind-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-homebind-smoke.log}"
  mode_args=(--homebind-smoke --homebind-timeout "$homebind_timeout_secs")
  if [[ -n "${WOW_BOT_HOMEBIND_RUNTIME_COUNTER:-}" ]]; then
    mode_args+=(--homebind-runtime-counter "$WOW_BOT_HOMEBIND_RUNTIME_COUNTER")
  fi
elif ((inventory_swap_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-inventory-swap-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-inventory-swap-smoke.log}"
  mode_args=(--inventory-swap-smoke --inventory-swap-timeout "$inventory_swap_timeout_secs")
  if [[ -n "${WOW_BOT_INVENTORY_SWAP_ITEM_ENTRY_A:-}" ]]; then
    mode_args+=(--inventory-swap-item-entry-a "$WOW_BOT_INVENTORY_SWAP_ITEM_ENTRY_A")
  fi
  if [[ -n "${WOW_BOT_INVENTORY_SWAP_ITEM_ENTRY_B:-}" ]]; then
    mode_args+=(--inventory-swap-item-entry-b "$WOW_BOT_INVENTORY_SWAP_ITEM_ENTRY_B")
  fi
elif ((vendor_requested)); then
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-vendor-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-vendor-smoke.log}"
  mode_args=(
    --vendor-smoke
    --vendor-entry "${WOW_BOT_VENDOR_ENTRY:-18525}"
    --vendor-spawn-guid "${WOW_BOT_VENDOR_SPAWN_GUID:-96654}"
    --vendor-item-entry "${WOW_BOT_VENDOR_ITEM_ENTRY:-30183}"
    --vendor-extended-cost "${WOW_BOT_VENDOR_EXTENDED_COST:-1642}"
    --vendor-currency-id "${WOW_BOT_VENDOR_CURRENCY_ID:-42}"
    --vendor-currency-cost "${WOW_BOT_VENDOR_CURRENCY_COST:-15}"
    --vendor-currency-quantity "${WOW_BOT_VENDOR_CURRENCY_QUANTITY:-30}"
    --vendor-timeout "$vendor_timeout_secs"
  )
  if [[ -n "${WOW_BOT_VENDOR_RUNTIME_COUNTER:-}" ]]; then
    mode_args+=(--vendor-runtime-counter "$WOW_BOT_VENDOR_RUNTIME_COUNTER")
  fi
elif ((quest_requested)); then
  : "${WOW_BOT_QUEST_CREATURE_ENTRY:?Set WOW_BOT_QUEST_CREATURE_ENTRY for quest-smoke mode}"
  report_path="${WOW_BOT_REPORT:-/tmp/rustycore-bot-quest-smoke-report.json}"
  log_path="${WOW_BOT_LOG:-/tmp/rustycore-bot-quest-smoke.log}"
  mode_args=(--quest-smoke --quest-creature-entry "$WOW_BOT_QUEST_CREATURE_ENTRY" --quest-timeout "$quest_timeout_secs")
  if [[ -n "${WOW_BOT_QUEST_CREATURE_GUID:-}" ]]; then
    mode_args+=(--quest-creature-guid "$WOW_BOT_QUEST_CREATURE_GUID")
  fi
  quest_runtime_counter="${WOW_BOT_QUEST_RUNTIME_COUNTER:-${WOW_BOT_QUEST_GUID_COUNTER:-}}"
  if [[ -n "$quest_runtime_counter" ]]; then
    mode_args+=(--quest-runtime-counter "$quest_runtime_counter")
  fi
  if [[ -n "${WOW_BOT_QUEST_MAP_ID:-}" ]]; then
    mode_args+=(--quest-map "$WOW_BOT_QUEST_MAP_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_EXPECT_ID:-}" ]]; then
    mode_args+=(--expect-quest "$WOW_BOT_QUEST_EXPECT_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_FORBID_ID:-}" ]]; then
    mode_args+=(--forbid-quest "$WOW_BOT_QUEST_FORBID_ID")
  fi
  if [[ -n "${WOW_BOT_QUEST_FORBID_TITLE_CONTAINS:-}" ]]; then
    mode_args+=(--forbid-title "$WOW_BOT_QUEST_FORBID_TITLE_CONTAINS")
  fi
  if [[ "${WOW_BOT_QUEST_QUERY_DETAILS:-1}" =~ ^(0|false|FALSE|no|NO|off|OFF)$ ]]; then
    mode_args+=(--no-quest-query-details)
  fi
  if [[ "${WOW_BOT_QUEST_ACCEPT:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-accept)
  fi
  if [[ "${WOW_BOT_QUEST_RESET:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-reset)
  fi
  if [[ "${WOW_BOT_QUEST_RELOCATE:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    mode_args+=(--quest-relocate)
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_LEVEL:-}" ]]; then
    mode_args+=(--quest-set-level "$WOW_BOT_QUEST_SET_LEVEL")
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_RACE:-}" ]]; then
    mode_args+=(--quest-set-race "$WOW_BOT_QUEST_SET_RACE")
  fi
  if [[ -n "${WOW_BOT_QUEST_SET_CLASS:-}" ]]; then
    mode_args+=(--quest-set-class "$WOW_BOT_QUEST_SET_CLASS")
  fi
  if [[ "${WOW_BOT_QUEST_OBJECTIVE_PERSIST:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    : "${WOW_BOT_QUEST_OBJECTIVES:?Set WOW_BOT_QUEST_OBJECTIVES for quest objective persistence QA}"
    mode_args+=(--quest-objective-persist --quest-objectives "$WOW_BOT_QUEST_OBJECTIVES")
  fi
  if [[ -n "${WOW_BOT_QUEST_OBJECTIVE_STATUS:-}" ]]; then
    mode_args+=(--quest-objective-status "$WOW_BOT_QUEST_OBJECTIVE_STATUS")
  fi
fi

bot_exec="${WOW_BOT_EXEC:-}"
if [[ -n "$bot_exec" ]]; then
  if [[ "$bot_exec" != /* ]]; then
    echo "WOW_BOT_EXEC must be an absolute path" >&2
    exit 2
  fi
  canonical_bot_exec="$(realpath --canonicalize-existing -- "$bot_exec")" || {
    echo "WOW_BOT_EXEC does not resolve to an existing path" >&2
    exit 2
  }
  if [[ "$canonical_bot_exec" != "$bot_exec" || ! -f "$bot_exec" || ! -x "$bot_exec" || -L "$bot_exec" ]]; then
    echo "WOW_BOT_EXEC must be a canonical, regular, executable file (not a symlink)" >&2
    exit 2
  fi
  expected_bot_sha="${WOW_BOT_EXEC_SHA256:-}"
  if [[ ! "$expected_bot_sha" =~ ^[[:xdigit:]]{64}$ ]]; then
    echo "WOW_BOT_EXEC_SHA256 must contain the expected 64-digit SHA-256" >&2
    exit 2
  fi
  expected_bot_sha="${expected_bot_sha,,}"
  actual_bot_sha="$(sha256sum -- "$bot_exec" | awk '{print $1}')"
  if [[ "$actual_bot_sha" != "$expected_bot_sha" ]]; then
    echo "WOW_BOT_EXEC SHA-256 mismatch" >&2
    exit 2
  fi
elif [[ -n "${WOW_BOT_EXEC_SHA256:-}" ]]; then
  echo "WOW_BOT_EXEC_SHA256 requires WOW_BOT_EXEC" >&2
  exit 2
else
  cargo +1.88.0 build --locked --bin wow-test-bot
  bot_exec="$PWD/target/debug/wow-test-bot"
fi

ensure_args=()
if [[ "$ensure_accounts" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
  ensure_args+=(--ensure-test-accounts)
fi

selection_args=(--single "$account")
smoke_subject="$account"
if ((loot_race_requested || loot_item_capture_requested)); then
  selection_args=()
  if ((loot_item_capture_requested)); then
    smoke_subject="TESTBOT2@bot.local (single-session item capture)"
  else
    smoke_subject="TESTBOT2@bot.local and TESTBOT3@bot.local"
  fi
fi

bot_command=(
  "$bot_exec"
  --config "${WOW_BOT_CONFIG:-config.example.json}"
  "${selection_args[@]}"
  "${mode_args[@]}"
  "${ensure_args[@]}"
  --no-cleanup-groups
  --no-auto-teleport
  --report "$report_path"
)

if ((RC_CALLER_XTRACE)); then
  set -x
fi

if ((loot_race_requested || loot_item_capture_requested)); then
  # Preserve PID ownership across the shell boundary. TERM/INT reaches the
  # Rust handler installed before fixture mutation, and SIGKILL cannot leave a
  # detached bot child continuing to mutate the durable fixture.
  exec "${bot_command[@]}" >"$log_path" 2>&1
fi

"${bot_command[@]}" >"$log_path" 2>&1

echo "RustyCore smoke passed for $smoke_subject"
echo "log: $log_path"
echo "report: $report_path"

if command -v jq >/dev/null 2>&1; then
  jq '{login_only, quest_smoke, stand_state_smoke, bank_smoke, homebind_smoke, inventory_swap_smoke, vendor_smoke, rested_xp_smoke, loot_race_smoke, results: [.results[] | {account, world_auth, enum_characters, player_login_verified, stand_state_smoke, stand_state_smoke_passed, stand_states_requested, stand_states_confirmed, stand_state_failure, bank_smoke, bank_smoke_passed, bank_banker_entry, bank_banker_spawn_guid, bank_banker_guid_counter, bank_item_guid, bank_item_entry, bank_inventory_slot, bank_bank_slot, bank_open_confirmed, bank_deposit_persisted, bank_relogin_after_deposit, bank_withdraw_persisted, bank_failure, homebind_smoke, homebind_smoke_passed, homebind_innkeeper_entry, homebind_innkeeper_spawn_guid, homebind_innkeeper_guid_counter, homebind_spell_go_seen, homebind_bind_point_update_seen, homebind_player_bound_seen, homebind_gossip_complete_seen, homebind_db_persisted, homebind_relogin_verified, homebind_failure, inventory_swap_smoke, inventory_swap_smoke_passed, inventory_swap_item_guid_a, inventory_swap_item_guid_b, inventory_swap_item_entry_a, inventory_swap_item_entry_b, inventory_swap_slot_a, inventory_swap_slot_b, inventory_swap_validation_gate_seen, inventory_swap_forward_persisted, inventory_swap_relogin_after_forward, inventory_swap_reverse_persisted, inventory_swap_relogin_after_reverse, inventory_swap_item_create_sha256, inventory_swap_item_create_relogin_verified, inventory_swap_item_metadata_persisted, inventory_swap_failure, vendor_smoke, vendor_smoke_passed, vendor_entry, vendor_spawn_guid, vendor_runtime_counter, vendor_item_entry, vendor_extended_cost, vendor_currency_id, vendor_currency_before, vendor_currency_after, vendor_item_total_after, vendor_inventory_seen, vendor_buy_succeeded_seen, vendor_set_currency_seen, vendor_item_push_seen, vendor_relogin_verified, vendor_failure, rested_xp_smoke, rested_xp_smoke_passed, rested_xp_offline_wilderness_bonus, rested_xp_offline_resting_bonus, rested_xp_target_entry, rested_xp_target_spawn_guid, rested_xp_target_guid_counter, rested_xp_packet_amount, rested_xp_packet_original, rested_xp_db_xp_before, rested_xp_db_xp_after, rested_xp_db_rest_before, rested_xp_db_rest_after, rested_xp_relog_verified, rested_xp_failure, loot_race_smoke, loot_race_smoke_passed, loot_race_target_entry, loot_race_target_spawn_guid, loot_race_target_runtime_counter, loot_race_party_confirmed, loot_race_target_discovered, loot_race_loot_opened, loot_race_loot_list_id, loot_race_loot_coins, loot_race_item_push_seen, loot_race_loot_removed_seen, loot_race_money_notify_amount, loot_race_coin_removed_seen, loot_race_db_item_total, loot_race_db_money_delta, loot_race_relog_verified, loot_race_failure, quest_smoke_passed, quest_target_entry, quest_target_spawn_guid, quest_target_guid_counter, quest_ids_seen, quest_titles_seen, quest_accept_sent, quest_accept_confirm_seen, quest_db_verified, quest_db_status, quest_failure, join_result}]}' "$report_path"
  if ((void_storage_requested || void_storage_query_capture_requested)); then
    jq '{void_storage_smoke, void_storage_query_capture, results: [.results[] | {account, void_storage_smoke, void_storage_smoke_passed, void_storage_query_capture, void_storage_query_capture_passed, void_storage_item_id, void_storage_unlock_persisted, void_storage_deposit_persisted, void_storage_deposit_relogin_verified, void_storage_swap_persisted, void_storage_swap_relogin_verified, void_storage_withdraw_persisted, void_storage_withdraw_relogin_verified, void_storage_failure}]}' "$report_path"
  fi
fi
