//! Synthetic target shapes only; no copied DB/account values or client text.
use wow_data::forever_spells::*;
use wow_persistence::forever::spells::server::{ServerSpellEffectRow, ServerSpellRow};

pub(super) fn server_effect(spell: u32, difficulty: i32) -> ServerSpellEffectRow {
    ServerSpellEffectRow {
        spell_id: spell,
        effect_index: 0,
        difficulty_id: difficulty,
        effect: 0,
        effect_aura: 0,
        effect_amplitude: 0.0,
        effect_attributes: 0,
        effect_aura_period: 0,
        effect_bonus_coefficient: 0.0,
        effect_chain_amplitude: 0.0,
        effect_chain_targets: 0,
        effect_item_type: 0,
        effect_mechanic: 0,
        effect_points_per_resource: 0.0,
        effect_pos_facing: 0.0,
        effect_real_points_per_level: 0.0,
        effect_trigger_spell: 0,
        bonus_coefficient_from_ap: 0.0,
        pvp_multiplier: 0.0,
        coefficient: 0.0,
        variance: 0.0,
        resource_coefficient: 0.0,
        group_size_base_points_coefficient: 0.0,
        effect_base_points: 0.0,
        effect_misc_value: [0; 2],
        effect_radius_index: [0; 2],
        effect_spell_class_mask: [0; 4],
        implicit_target: [0; 2],
    }
}

pub(super) fn server_spell(spell: u32, difficulty: i32) -> ServerSpellRow {
    ServerSpellRow {
        id: spell,
        difficulty_id: difficulty,
        category_id: 0,
        dispel: 0,
        mechanic: 0,
        attributes: [0; 17],
        stances: 0,
        stances_not: 0,
        targets: 0,
        target_creature_type: 0,
        requires_spell_focus: 0,
        facing_caster_flags: 0,
        caster_aura_state: 0,
        target_aura_state: 0,
        exclude_caster_aura_state: 0,
        exclude_target_aura_state: 0,
        caster_aura_spell: 0,
        target_aura_spell: 0,
        exclude_caster_aura_spell: 0,
        exclude_target_aura_spell: 0,
        caster_aura_type: 0,
        target_aura_type: 0,
        exclude_caster_aura_type: 0,
        exclude_target_aura_type: 0,
        casting_time_index: 0,
        recovery_time: 0,
        category_recovery_time: 0,
        start_recovery_category: 0,
        start_recovery_time: 0,
        interrupt_flags: 0,
        aura_interrupt_flags: [0; 2],
        channel_interrupt_flags: [0; 2],
        proc_flags: [0; 2],
        proc_chance: 0,
        proc_charges: 0,
        proc_cooldown: 0,
        proc_base_ppm: 0.0,
        max_level: 0,
        base_level: 0,
        spell_level: 0,
        duration_index: 0,
        range_index: 0,
        speed: 0.0,
        launch_delay: 0.0,
        stack_amount: 0,
        equipped_item_class: 0,
        equipped_item_sub_class_mask: 0,
        equipped_item_inventory_type_mask: 0,
        content_tuning_id: 0,
        spell_name: Vec::new(),
        cone_angle: 0.0,
        cone_width: 0.0,
        max_target_level: 0,
        max_affected_targets: 0,
        spell_family_name: 0,
        spell_family_flags: [0; 4],
        dmg_class: 0,
        prevention_type: 0,
        area_group_id: 0,
        school_mask: 0,
        charge_category_id: 0,
    }
}

pub(super) fn client_rows() -> SpellRecords {
    SpellRecords {
        spell_names: vec![SpellNameRecord {
            id: 1,
            name: SpellText::from_locale(6, vec![0xFF, 0, b'x']).unwrap(),
        }],
        spell_aura_options: vec![SpellAuraOptionsRecord {
            id: 1,
            difficulty_id: 0,
            cumulative_aura: u16::MAX,
            proc_category_recovery: i32::MIN,
            proc_chance: u8::MAX,
            proc_charges: i32::MIN,
            spell_procs_per_minute_id: u16::MAX,
            proc_type_mask: [i32::MIN; 2],
            spell_id: 1,
        }],
        spell_aura_restrictions: vec![SpellAuraRestrictionsRecord {
            id: 1,
            difficulty_id: 0,
            caster_aura_state: i32::MIN,
            target_aura_state: i32::MIN,
            exclude_caster_aura_state: i32::MIN,
            exclude_target_aura_state: i32::MIN,
            caster_aura_spell: i32::MIN,
            target_aura_spell: i32::MIN,
            exclude_caster_aura_spell: i32::MIN,
            exclude_target_aura_spell: i32::MIN,
            caster_aura_type: i16::MIN,
            target_aura_type: i16::MIN,
            exclude_caster_aura_type: i16::MIN,
            exclude_target_aura_type: i16::MIN,
            spell_id: 1,
        }],
        spell_casting_requirements: vec![SpellCastingRequirementsRecord {
            id: 1,
            spell_id: 1,
            facing_caster_flags: i32::MIN,
            min_faction_id: u16::MAX,
            min_reputation: i32::MIN,
            required_areas_id: u16::MAX,
            required_aura_vision: u8::MAX,
            requires_spell_focus: u16::MAX,
        }],
        spell_categories: vec![SpellCategoriesRecord {
            id: 1,
            difficulty_id: 0,
            category: i16::MIN,
            defense_type: i8::MIN,
            diminish_type: i32::MIN,
            dispel_type: i8::MIN,
            mechanic: i8::MIN,
            prevention_type: i32::MIN,
            start_recovery_category: i16::MIN,
            charge_category: i16::MIN,
            spell_id: 1,
        }],
        spell_class_options: vec![SpellClassOptionsRecord {
            id: 1,
            spell_id: 1,
            modal_next_spell: u32::MAX,
            spell_class_set: i32::MIN,
            spell_class_mask: [u32::MAX; 4],
        }],
        spell_cooldowns: vec![SpellCooldownsRecord {
            id: 1,
            difficulty_id: 0,
            category_recovery_time: i32::MIN,
            recovery_time: i32::MIN,
            start_recovery_time: i32::MIN,
            aura_spell_id: i32::MIN,
            spell_id: 1,
        }],
        spell_equipped_items: vec![SpellEquippedItemsRecord {
            id: 1,
            spell_id: 1,
            equipped_item_class: i32::MIN,
            equipped_item_inv_types: i32::MIN,
            equipped_item_subclass: i32::MIN,
        }],
        spell_interrupts: vec![SpellInterruptsRecord {
            id: 1,
            difficulty_id: 0,
            interrupt_flags: i32::MIN,
            aura_interrupt_flags: [i32::MIN; 2],
            channel_interrupt_flags: [i32::MIN; 2],
            spell_id: 1,
        }],
        spell_levels: vec![SpellLevelsRecord {
            id: 1,
            difficulty_id: 0,
            max_level: i16::MIN,
            max_passive_aura_level: u8::MAX,
            base_level: i32::MIN,
            spell_level: i32::MIN,
            spell_id: 1,
        }],
        spell_misc: vec![SpellMiscRecord {
            id: 1,
            attributes: [i32::MIN; 17],
            difficulty_id: 0,
            casting_time_index: u16::MAX,
            duration_index: u16::MAX,
            pv_p_duration_index: u16::MAX,
            range_index: u16::MAX,
            school_mask: u8::MAX,
            speed: f32::from_bits(0x7FC0_1234),
            launch_delay: f32::from_bits(0x7FC0_1234),
            min_duration: f32::from_bits(0x7FC0_1234),
            spell_icon_file_data_id: i32::MIN,
            active_icon_file_data_id: i32::MIN,
            content_tuning_id: i32::MIN,
            show_future_spell_player_condition_id: i32::MIN,
            spell_visual_script: i32::MIN,
            active_spell_visual_script: i32::MIN,
            spell_id: 1,
        }],
        spell_reagents: vec![SpellReagentsRecord {
            id: 1,
            spell_id: 1,
            reagent: [i32::MIN; 8],
            reagent_count: [i16::MIN; 8],
            reagent_recraft_count: [i16::MIN; 8],
            reagent_source: [u8::MAX; 8],
        }],
        spell_scaling: vec![SpellScalingRecord {
            id: 1,
            spell_id: 1,
            min_scaling_level: u32::MAX,
            max_scaling_level: u32::MAX,
        }],
        spell_shapeshifts: vec![SpellShapeshiftRecord {
            id: 1,
            spell_id: 1,
            stance_bar_order: i8::MIN,
            shapeshift_exclude: [i32::MIN; 2],
            shapeshift_mask: [i32::MIN; 2],
        }],
        spell_target_restrictions: vec![SpellTargetRestrictionsRecord {
            id: 1,
            difficulty_id: 0,
            cone_degrees: f32::from_bits(0x7FC0_1234),
            max_targets: u8::MAX,
            max_target_level: u32::MAX,
            target_creature_type: i16::MIN,
            targets: i32::MIN,
            width: f32::from_bits(0x7FC0_1234),
            spell_id: 1,
        }],
        spell_totems: vec![SpellTotemsRecord {
            id: 1,
            spell_id: 1,
            required_totem_category_id: [u16::MAX; 2],
            totem: [i32::MIN; 2],
        }],
        spell_effects: vec![SpellEffectRecord {
            id: 1,
            effect_aura: 664,
            difficulty_id: 0,
            effect_index: 2,
            effect: 360,
            effect_amplitude: f32::from_bits(0x7FC0_1234),
            effect_attributes: i32::MIN,
            effect_aura_period: i32::MIN,
            effect_bonus_coefficient: f32::from_bits(0x7FC0_1234),
            effect_chain_amplitude: f32::from_bits(0x7FC0_1234),
            effect_chain_targets: i32::MIN,
            effect_item_type: i32::MIN,
            effect_mechanic: i32::MIN,
            effect_points_per_resource: f32::from_bits(0x7FC0_1234),
            effect_pos_facing: f32::from_bits(0x7FC0_1234),
            effect_real_points_per_level: f32::from_bits(0x7FC0_1234),
            effect_trigger_spell: i32::MIN,
            bonus_coefficient_from_ap: f32::from_bits(0x7FC0_1234),
            pvp_multiplier: f32::from_bits(0x7FC0_1234),
            coefficient: f32::from_bits(0x7FC0_1234),
            variance: f32::from_bits(0x7FC0_1234),
            resource_coefficient: f32::from_bits(0x7FC0_1234),
            group_size_base_points_coefficient: f32::from_bits(0x7FC0_1234),
            effect_base_points: f32::from_bits(0x7FC0_1234),
            scaling_class: i32::MIN,
            target_node_graph: i32::MIN,
            effect_misc_value: [i32::MIN; 2],
            effect_radius_index: [0, 99],
            effect_spell_class_mask: [u32::MAX; 4],
            implicit_target: [152; 2],
            spell_id: 1,
        }],
        spell_cast_times: vec![SpellCastTimesRecord {
            id: 65535,
            base: 1,
            minimum: 2,
        }],
        spell_durations: vec![SpellDurationRecord {
            id: 65535,
            duration: 1,
            max_duration: 2,
            duration_per_resource: 3,
        }],
        spell_ranges: vec![SpellRangeRecord {
            id: 65535,
            display_name: SpellText::default(),
            display_name_short: SpellText::default(),
            flags: 0,
            range_min: [1.0; 2],
            range_max: [2.0; 2],
        }],
        spell_procs_per_minute: vec![SpellProcsPerMinuteRecord {
            id: 65535,
            base_proc_rate: 1.0,
            flags: 0,
        }],
        spell_procs_per_minute_mods: vec![SpellProcsPerMinuteModRecord {
            id: 1,
            r#type: 1,
            param: 2,
            coeff: 3.0,
            field_12_1_5_69594_003: 4,
            spell_procs_per_minute_id: 65535,
        }],
        spell_radii: vec![SpellRadiusRecord {
            id: 0,
            radius: 1.0,
            radius_per_level: 2.0,
            radius_min: 3.0,
            radius_max: 4.0,
        }],
        spell_labels: vec![SpellLabelRecord {
            id: 1,
            label_id: 5,
            spell_id: 1,
        }],
        spell_empowers: vec![SpellEmpowerRecord {
            id: 1,
            spell_id: 1,
            unused1000: 0,
        }],
        spell_empower_stages: vec![SpellEmpowerStageRecord {
            id: 1,
            stage: 0,
            duration_ms: -1,
            spell_empower_id: 1,
        }],
        spell_reagents_currencies: vec![SpellReagentsCurrencyRecord {
            id: 1,
            spell_id: 1,
            currency_types_id: 2,
            currency_count: 3,
            override_recraft_currency_count: 4,
            order_source: 5,
        }],
        spell_powers: vec![SpellPowerRecord {
            id: 1,
            order_index: 0,
            mana_cost: i32::MIN,
            mana_cost_per_level: i32::MIN,
            mana_per_second: i32::MIN,
            power_display_id: u32::MAX,
            alt_power_bar_id: i32::MIN,
            power_cost_pct: f32::from_bits(0x7FC0_1234),
            power_cost_max_pct: f32::from_bits(0x7FC0_1234),
            optional_cost_pct: f32::from_bits(0x7FC0_1234),
            power_pct_per_second: f32::from_bits(0x7FC0_1234),
            power_type: i8::MIN,
            required_aura_spell_id: i32::MIN,
            optional_cost: u32::MAX,
            spell_id: 1,
        }],
        spell_x_spell_visuals: vec![SpellXSpellVisualRecord {
            id: 1,
            difficulty_id: 0,
            spell_visual_id: u32::MAX,
            probability: f32::from_bits(0x7FC0_1234),
            flags: i32::MIN,
            priority: i32::MIN,
            spell_icon_file_id: i32::MIN,
            active_icon_file_id: i32::MIN,
            viewer_unit_condition_id: u16::MAX,
            viewer_player_condition_id: u32::MAX,
            caster_unit_condition_id: u16::MAX,
            caster_player_condition_id: u32::MAX,
            spell_id: 1,
        }],
        ..Default::default()
    }
}
