//! Required immutable session catalog capabilities, in field evaluation order.

use crate::session_resources::*;
use crate::{
    REALM_TYPE_NORMAL_LIKE_CPP, is_ffa_pvp_realm_type_like_cpp, is_pvp_realm_type_like_cpp,
    max_primary_trade_skills_like_cpp, world_config_bool, world_config_u8, world_config_u32,
};
use std::sync::Arc;

pub(super) fn build_inventory(
    inventory: &super::inventory_catalogs::InventoryBaseCatalogs,
    world_spawns: &super::world_object_startup::WorldSpawnStartup,
    item_search_name_store: &Arc<wow_data::ItemSearchNameStore>,
    trinity_string_store: &Arc<wow_data::TrinityStringStoreLikeCpp>,
    collections: &super::collection_startup::CollectionCatalogs,
    stat_tables: &super::stat_tables_startup::StatTables,
    data_dir: &str,
    transmog_set_item_store: &Arc<wow_data::TransmogSetItemStore>,
    player_creation: &super::player_creation_startup::PlayerCreationStartup,
    item_auxiliary: &super::item_auxiliary_catalogs::ItemAuxiliaryCatalogs,
    loot: &super::loot_startup::LootCatalogs,
) -> anyhow::Result<SessionInventoryCapabilitiesLikeCpp> {
    Ok(SessionInventoryCapabilitiesLikeCpp {
        currency_types_store: Arc::clone(&inventory.currency_types_store),
        item_extended_cost_store: Arc::clone(&inventory.item_extended_cost_store),
        item_store: Arc::clone(&inventory.item_store),
        item_child_equipment_store: Arc::clone(&inventory.item_child_equipment_store),
        item_appearance_store: Arc::clone(&world_spawns.item_appearance_store),
        item_modified_appearance_store: Arc::clone(&world_spawns.item_modified_appearance_store),
        item_search_name_store: Arc::clone(item_search_name_store),
        trinity_string_store: Arc::clone(trinity_string_store),
        heirloom_store: Arc::clone(&collections.heirloom_store),
        toy_store: Arc::clone(&collections.toy_store),
        combat_ratings_game_table: Arc::clone(&stat_tables.combat_ratings_game_table),
        regen_game_tables: crate::session_resources::load_regen_game_tables(data_dir)?,
        shield_block_regular_game_table: Arc::clone(&stat_tables.shield_block_regular_game_table),
        transmog_set_item_store: Arc::clone(transmog_set_item_store),
        item_limit_category_store: Arc::clone(&inventory.item_limit_category_store),
        item_limit_category_condition_store: Arc::clone(
            &inventory.item_limit_category_condition_store,
        ),
        player_stats: Arc::clone(&player_creation.stats),
        item_bonus_db2_store: Arc::clone(&inventory.item_bonus_db2_store),
        pvp_item_store: Arc::clone(&inventory.pvp_item_store),
        item_set_store: Arc::clone(&inventory.item_set_store),
        item_set_spell_store: Arc::clone(&inventory.item_set_spell_store),
        item_stats_store: Arc::clone(&world_spawns.item_stats_store),
        durability_costs_store: Arc::clone(&item_auxiliary.durability_costs_store),
        durability_quality_store: Arc::clone(&item_auxiliary.durability_quality_store),
        item_effect_store: Arc::clone(&item_auxiliary.item_effect_store),
        item_random_suffix_store: Arc::clone(&item_auxiliary.item_random_suffix_store),
        item_random_properties_store: Arc::clone(&item_auxiliary.item_random_properties_store),
        item_spec_override_store: Arc::clone(&item_auxiliary.item_spec_override_store),
        rand_prop_points_store: Arc::clone(&item_auxiliary.rand_prop_points_store),
        item_random_enchantment_template_store: Arc::clone(
            &item_auxiliary.item_random_enchantment_template_store,
        ),
        loot_stores: Arc::clone(&loot.loot_stores),
    })
}

pub(super) fn build_player(
    condition_store: &Arc<wow_data::ConditionEntriesByTypeStore>,
    condition_references: &super::condition_reference_startup::ConditionReferences,
    scaling: &super::scaling_startup::ScalingCatalogs,
    disable_mgr: &Arc<wow_data::DisableMgrLikeCpp>,
    creature_runtime: &super::creature_catalog_startup::CreatureRuntimeCatalogs,
    item_auxiliary: &super::item_auxiliary_catalogs::ItemAuxiliaryCatalogs,
    skills: &super::skill_catalogs::SkillCatalogs,
    player_catalogs: &super::player_catalog_startup::PlayerCatalogs,
) -> SessionPlayerCatalogCapabilitiesLikeCpp {
    SessionPlayerCatalogCapabilitiesLikeCpp {
        condition_store: Arc::clone(condition_store),
        player_condition_store: Arc::clone(&condition_references.player_condition_store),
        content_tuning_store: Arc::clone(&condition_references.content_tuning_store),
        curve_store: Arc::clone(&scaling.curve_store),
        curve_point_store: Arc::clone(&scaling.curve_point_store),
        scaling_stat_distribution_store: Arc::clone(&scaling.scaling_stat_distribution_store),
        scaling_stat_values_store: Arc::clone(&scaling.scaling_stat_values_store),
        disable_mgr: Arc::clone(disable_mgr),
        difficulty_store: Arc::clone(&creature_runtime.difficulty_store),
        lock_store: Arc::clone(&item_auxiliary.lock_store),
        spell_item_enchantment_store: Arc::clone(&item_auxiliary.spell_item_enchantment_store),
        spell_item_enchantment_condition_store: Arc::clone(
            &item_auxiliary.spell_item_enchantment_condition_store,
        ),
        gem_properties_store: Arc::clone(&item_auxiliary.gem_properties_store),
        skill_store: Arc::clone(&skills.skill_store),
        trait_definition_store: Arc::clone(&skills.trait_definition_store),
        trait_definition_locale_store: Arc::clone(&skills.trait_definition_locale_store),
        trait_currency_source_locale_store: Arc::clone(&skills.trait_currency_source_locale_store),
        trait_tree_skill_line_index: Arc::clone(&skills.trait_tree_skill_line_index),
        skill_line_store: Arc::clone(&skills.skill_line_store),
        skill_tiers_store: Arc::clone(&player_catalogs.skill_tiers_store),
        talent_store: Arc::clone(&player_catalogs.talent_store),
        num_talents_at_level_store: Arc::clone(&player_catalogs.num_talents_at_level_store),
        chr_races_store: Arc::clone(&player_catalogs.chr_races_store),
        chr_classes_store: Arc::clone(&player_catalogs.chr_classes_store),
        power_type_store: Arc::clone(&player_catalogs.power_type_store),
    }
}

pub(super) fn build_spells(
    spell_acquisition: &super::spell_acquisition_startup::SpellAcquisitionCatalogs,
    spell_store: &Arc<wow_data::SpellStore>,
    spell_world: &super::spell_world_startup::SpellWorldStartup,
    spell_levels_store: &Arc<wow_data::SpellLevelsStore>,
    spell_info: &super::spell_info_startup::SpellInfoStartup,
    npc_spell_click_store: &Arc<wow_data::NpcSpellClickStoreLikeCpp>,
    spell_area_store: &Arc<wow_data::SpellAreaStoreLikeCpp>,
    spell_duration_store: &Arc<wow_data::SpellDurationStore>,
    movie_store: &Arc<wow_data::MovieStore>,
    world_spawns: &super::world_object_startup::WorldSpawnStartup,
) -> SessionSpellCatalogCapabilitiesLikeCpp {
    SessionSpellCatalogCapabilitiesLikeCpp {
        spell_chain_store: Arc::clone(&spell_acquisition.spell_chain_store),
        spell_store: Arc::clone(spell_store),
        spell_acquisition_catalog: Arc::clone(&spell_acquisition.spell_acquisition_catalog),
        spell_acquisition_safe_cast_spell_ids: Arc::clone(
            &spell_world.spell_acquisition_safe_cast_spell_ids,
        ),
        spell_acquisition_valid_craft_spell_ids: Arc::clone(
            &spell_world.spell_acquisition_valid_craft_spell_ids,
        ),
        spell_script_exact_spell_ids: Arc::clone(&spell_world.spell_script_exact_spell_ids),
        spell_script_all_rank_root_spell_ids: Arc::clone(
            &spell_world.spell_script_all_rank_root_spell_ids,
        ),
        legacy_spell_script_spell_ids: Arc::clone(&spell_world.legacy_spell_script_spell_ids),
        spell_linked_rejected_trigger_spell_ids: Arc::clone(
            &spell_world.spell_linked_rejected_trigger_spell_ids,
        ),
        spell_levels_store: Arc::clone(spell_levels_store),
        spell_category_store: Arc::clone(&spell_info.spell_category_store),
        spell_class_options_store: Arc::clone(&spell_info.spell_class_options_store),
        spell_label_store: Arc::clone(&spell_info.spell_label_store),
        npc_spell_click_store: Arc::clone(npc_spell_click_store),
        spell_aura_options_store: Arc::clone(&spell_info.spell_aura_options_store),
        spell_aura_restrictions_store: Arc::clone(&spell_info.spell_aura_restrictions_store),
        spell_target_restrictions_store: Arc::clone(&spell_info.spell_target_restrictions_store),
        spell_equipped_items_store: Arc::clone(&spell_info.spell_equipped_items_store),
        spell_misc_store: Arc::clone(&spell_info.spell_misc_store),
        spell_group_store: Arc::clone(&spell_world.spell_group_store),
        spell_group_stack_rule_store: Arc::clone(&spell_world.spell_group_stack_rule_store),
        spell_linked_store: Arc::clone(&spell_world.spell_linked_store),
        spell_pet_aura_store: Arc::clone(&spell_world.spell_pet_aura_store),
        spell_area_store: Arc::clone(spell_area_store),
        spell_custom_attribute_store: Arc::clone(&spell_acquisition.spell_custom_attribute_store),
        spell_learn_skill_store: Arc::clone(&spell_acquisition.spell_learn_skill_store),
        spell_learn_spell_store: Arc::clone(&spell_acquisition.spell_learn_spell_store),
        spell_proc_store: Arc::clone(&spell_world.spell_proc_store),
        spell_required_store: Arc::clone(&spell_world.spell_required_store),
        spell_threat_store: Arc::clone(&spell_world.spell_threat_store),
        spell_duration_store: Arc::clone(spell_duration_store),
        spell_radius_store: Arc::clone(&spell_acquisition.spell_radius_store),
        spell_range_store: Arc::clone(&spell_acquisition.spell_range_store),
        spell_target_position_store: Arc::clone(&spell_world.spell_target_position_store),
        movie_store: Arc::clone(movie_store),
        script_name_interner: Arc::clone(&world_spawns.script_name_interner),
    }
}

pub(super) fn build_world(
    geography: &super::geography_startup::GeographyBase,
    fishing_base_skill_store: &Arc<wow_data::FishingBaseSkillStoreLikeCpp>,
    chr_specialization_store: &Arc<wow_data::ChrSpecializationStore>,
    dungeon_encounter_store: &Arc<wow_data::DungeonEncounterStore>,
    map_difficulty_store: &Arc<wow_data::MapDifficultyStore>,
    map_difficulty_x_condition_store: &Arc<wow_data::MapDifficultyXConditionStore>,
    access_requirement_store: &Arc<wow_data::AccessRequirementStoreLikeCpp>,
    lfg_dungeons_store: &Arc<wow_data::LfgDungeonsStore>,
    creature_template_lifecycle_store: &Arc<wow_data::CreatureTemplateLifecycleStoreLikeCpp>,
    creature_runtime: &super::creature_catalog_startup::CreatureRuntimeCatalogs,
    gameobject_display_info_store: &Arc<wow_data::GameObjectDisplayInfoStore>,
    collections: &super::collection_startup::CollectionCatalogs,
    spell_shapeshift_form_store: &Arc<wow_data::SpellShapeshiftFormStore>,
    vehicles: &super::vehicle_catalogs::VehicleCatalogs,
    terrain_swap_store: &Arc<wow_data::TerrainSwapStore>,
    phase_store: &Arc<wow_data::PhaseStore>,
    phase_group_store: &Arc<wow_data::PhaseGroupStore>,
) -> SessionWorldCatalogCapabilitiesLikeCpp {
    SessionWorldCatalogCapabilitiesLikeCpp {
        area_table_store: Arc::clone(&geography.area_table_store),
        fishing_base_skill_store: Arc::clone(fishing_base_skill_store),
        chr_specialization_store: Arc::clone(chr_specialization_store),
        map_store: Arc::clone(&geography.map_store),
        dungeon_encounter_store: Arc::clone(dungeon_encounter_store),
        world_safe_loc_store: Arc::clone(&geography.world_safe_loc_store),
        map_difficulty_store: Arc::clone(map_difficulty_store),
        map_difficulty_x_condition_store: Arc::clone(map_difficulty_x_condition_store),
        access_requirement_store: Arc::clone(access_requirement_store),
        lfg_dungeons_store: Arc::clone(lfg_dungeons_store),
        creature_template_lifecycle_store: Arc::clone(creature_template_lifecycle_store),
        creature_template_mount_store: Arc::clone(&creature_runtime.creature_template_mount_store),
        creature_display_info_store: Arc::clone(&creature_runtime.creature_display_info_store),
        creature_display_info_extra_store: Arc::clone(
            &creature_runtime.creature_display_info_extra_store,
        ),
        gameobject_display_info_store: Arc::clone(gameobject_display_info_store),
        creature_model_info_store: Arc::clone(&creature_runtime.creature_model_info_store),
        creature_model_data_store: Arc::clone(&creature_runtime.creature_model_data_store),
        mount_store: Arc::clone(&collections.mount_store),
        mount_definition_store: Arc::clone(&collections.mount_definition_store),
        mount_capability_store: Arc::clone(&collections.mount_capability_store),
        mount_type_x_capability_store: Arc::clone(&collections.mount_type_x_capability_store),
        mount_x_display_store: Arc::clone(&collections.mount_x_display_store),
        spell_shapeshift_form_store: Arc::clone(spell_shapeshift_form_store),
        vehicle_store: Arc::clone(&vehicles.vehicle_store),
        vehicle_seat_store: Arc::clone(&vehicles.vehicle_seat_store),
        vehicle_accessory_store: Arc::clone(&vehicles.vehicle_accessory_store),
        terrain_swap_store: Arc::clone(terrain_swap_store),
        phase_store: Arc::clone(phase_store),
        phase_group_store: Arc::clone(phase_group_store),
    }
}

pub(super) fn build_progression(
    quest_rewards: &super::progression_catalog_startup::PlayerXpAndQuestRewards,
    quest_store: &Arc<wow_data::quest::QuestStore>,
    reputation: &super::progression_catalog_startup::QuestReputationCatalogs,
    world_configs: &wow_config::WorldConfigSet,
) -> SessionProgressionCapabilitiesLikeCpp {
    SessionProgressionCapabilitiesLikeCpp {
        quest_xp_store: Arc::clone(&quest_rewards.quest_xp_store),
        quest_money_reward_store: Arc::clone(&quest_rewards.quest_money_reward_store),
        quest_store: Arc::clone(quest_store),
        quest_v2_store: Arc::clone(&quest_rewards.quest_v2_store),
        quest_info_store: Arc::clone(&quest_rewards.quest_info_store),
        quest_package_item_store: Arc::clone(&quest_rewards.quest_package_item_store),
        quest_faction_reward_store: Arc::clone(&reputation.quest_faction_reward_store),
        progression_faction_store: Arc::clone(&reputation.progression_faction_store),
        faction_template_store: Arc::clone(&reputation.faction_template_store),
        friendship_rep_reaction_store: Arc::clone(&reputation.friendship_rep_reaction_store),
        paragon_reputation_store: Arc::clone(&reputation.paragon_reputation_store),
        reputation_reward_rate_store: Arc::clone(&reputation.reputation_reward_rate_store),
        creature_onkill_reputation_store: Arc::clone(&reputation.creature_onkill_reputation_store),
        reputation_spillover_template_store: Arc::clone(
            &reputation.reputation_spillover_template_store,
        ),
        min_quest_scaled_xp_ratio: world_config_u32(
            world_configs,
            "CONFIG_MIN_QUEST_SCALED_XP_RATIO",
            0,
        ),
        max_player_level_config: world_config_u32(world_configs, "CONFIG_MAX_PLAYER_LEVEL", 80),
        max_primary_trade_skills: max_primary_trade_skills_like_cpp(world_configs),
        is_pvp_realm: is_pvp_realm_type_like_cpp(world_config_u32(
            world_configs,
            "CONFIG_GAME_TYPE",
            u32::from(REALM_TYPE_NORMAL_LIKE_CPP),
        )),
        is_ffa_pvp_realm: is_ffa_pvp_realm_type_like_cpp(world_config_u32(
            world_configs,
            "CONFIG_GAME_TYPE",
            u32::from(REALM_TYPE_NORMAL_LIKE_CPP),
        )),
        max_recruit_a_friend_bonus_player_level: world_config_u32(
            world_configs,
            "CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL",
            85,
        ),
        max_recruit_a_friend_bonus_player_level_difference: world_config_u32(
            world_configs,
            "CONFIG_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL_DIFFERENCE",
            4,
        ),
    }
}
