// Generated by tools/modules/compose.py. Do not edit by hand.
// Copyright (c) 2026 alseif0x
// Licensed under GPL v3 — https://www.gnu.org/licenses/gpl-3.0.html

//! Composed world-server entry point for trusted linked modules.
//!
//! Registrars run in the operator's declared order, recorded in
//! `modules.lock.toml`. Ordering is explicit here and never relies on linker
//! inventory. Configuration is validated at sync and embedded, so no callback
//! reads a file. Installed modules, in composition order:
//!
//! No modules are installed.

use std::process::ExitCode;

use anyhow::Result;

#[tokio::main]
async fn main() -> Result<ExitCode> {
    let mut modules = wow_module_api::ModuleRegistry::new();
    // No modules are installed; this is the no-op compositor.
    world_server::run_with_modules(std::env::args().skip(1).collect(), modules).await
}
