//! SQL-free target numeric item DTOs, consumed once during composition.
//! 02245dcd HotfixDatabase.cpp:870-872,980-981,1067-1081,1104.
//! Five byte strings retain Source field order and main-table enUS ownership.
pub struct ItemRow {
    pub id: u32,
    pub class: i32,
    pub subclass: u8,
    pub material: u8,
    pub inventory_type: i8,
    pub sheathe: u8,
    pub pet_food: i32,
    pub sound_override: i8,
    pub icon_file: i32,
    pub group_sounds: u32,
    pub content_tuning: i32,
    pub modified_crafting_reagent: i32,
    pub unknown_1200: u8,
    pub crafting_quality: i32,
    pub squish_era: i32,
    pub recraft_reagent_percentage: f32,
    pub order_source: u8,
}
pub struct ItemEffectRow {
    pub id: u32,
    pub legacy_slot: u8,
    pub trigger: u8,
    pub charges: i16,
    pub cooldown: i32,
    pub category_cooldown: i32,
    pub spell_category: u16,
    pub spell: i32,
    pub specialization: u16,
    pub player_condition: i32,
}
pub struct ItemRelationRow {
    pub id: u32,
    pub effect: i32,
    pub item: u32,
}
pub struct SparseItemRow {
    pub id: u32,
    pub strings: [Vec<u8>; 5],
    pub expansion: i32,
    pub damage_variance: f32,
    pub limit_category: i32,
    pub duration: u32,
    pub quality_modifier: f32,
    pub bag_family: u32,
    pub start_quest: i32,
    pub language: i32,
    pub item_range: f32,
    pub socket_percentage: [f32; 10],
    pub stat_percent: [i32; 10],
    pub stat_bonus: [i32; 10],
    pub stackable: i32,
    pub max_count: i32,
    pub min_reputation: i32,
    pub required_ability: u32,
    pub allowable_race: [i32; 2],
    pub sell_price: u32,
    pub buy_price: u32,
    pub vendor_stack: u32,
    pub price_variance: f32,
    pub price_random: f32,
    pub flags: [i32; 5],
    pub faction_related: i32,
    pub modified_crafting_reagent: i32,
    pub content_tuning: i32,
    pub player_level_curve: i32,
    pub item_level_offset_curve: i32,
    pub item_level_offset: i32,
    pub squish_era: i32,
    pub name_description: u16,
    pub transmog_holiday: u16,
    pub holiday: u16,
    pub gem_properties: u16,
    pub socket_enchantment: u16,
    pub totem_category: u16,
    pub instance_bound: u16,
    pub zone_bound: [u16; 2],
    pub item_set: u16,
    pub lock: u16,
    pub page: u16,
    pub delay: u16,
    pub min_faction: u16,
    pub required_skill_rank: u16,
    pub required_skill: u16,
    pub item_level: u16,
    pub allowable_class: i16,
    pub artifact: u8,
    pub spell_weight: u8,
    pub spell_weight_category: u8,
    pub socket_type: [u8; 3],
    pub sheathe: u8,
    pub material: u8,
    pub page_material: u8,
    pub bonding: u8,
    pub damage_type: u8,
    pub container_slots: u8,
    pub required_pvp_medal: u8,
    pub required_pvp_rank: i8,
    pub required_level: i8,
    pub inventory_type: i8,
    pub quality: i8,
    pub ammunition: u8,
}
#[derive(Default)]
pub struct ItemRows {
    pub items: Vec<ItemRow>,
    pub sparse: Vec<SparseItemRow>,
    pub effects: Vec<ItemEffectRow>,
    pub relations: Vec<ItemRelationRow>,
}
pub struct ItemOverlays {
    pub official: ItemRows,
    pub custom: ItemRows,
}
pub struct SparseItemLocaleRow {
    pub id: u32,
    pub strings: [Vec<u8>; 5],
}
pub struct SparseItemLocaleOverlays {
    pub official: Vec<SparseItemLocaleRow>,
    pub custom: Vec<SparseItemLocaleRow>,
}
