//! Reviewed source SpellInfo.cpp:959-1323, 02245dcd; all 361 effect kinds.
//! This table is not an effect executor or client/protocol compatibility proof.
use super::{EffectTargetType as I, TargetObject as O};
pub(super) const EFFECTS: [(I, O); 361] = [
    (I::None, O::None),                   // 0
    (I::Explicit, O::Unit),               // 1
    (I::Explicit, O::Unit),               // 2
    (I::None, O::None),                   // 3
    (I::None, O::None),                   // 4
    (I::Explicit, O::Item),               // 5
    (I::Explicit, O::Unit),               // 6
    (I::Explicit, O::Unit),               // 7
    (I::Explicit, O::Unit),               // 8
    (I::Explicit, O::Unit),               // 9
    (I::Explicit, O::Unit),               // 10
    (I::Explicit, O::Unit),               // 11
    (I::None, O::None),                   // 12
    (I::Explicit, O::UnitAndDestination), // 13
    (I::Explicit, O::Unit),               // 14
    (I::Explicit, O::UnitAndDestination), // 15
    (I::Explicit, O::Unit),               // 16
    (I::Explicit, O::Unit),               // 17
    (I::Explicit, O::CorpseAlly),         // 18
    (I::Explicit, O::Unit),               // 19
    (I::None, O::Unit),                   // 20
    (I::None, O::Unit),                   // 21
    (I::None, O::Unit),                   // 22
    (I::None, O::Unit),                   // 23
    (I::Explicit, O::Unit),               // 24
    (I::None, O::Unit),                   // 25
    (I::None, O::Unit),                   // 26
    (I::Explicit, O::Destination),        // 27
    (I::Explicit, O::Destination),        // 28
    (I::Explicit, O::UnitAndDestination), // 29
    (I::None, O::Unit),                   // 30
    (I::Explicit, O::Unit),               // 31
    (I::None, O::None),                   // 32
    (I::Explicit, O::GameObjectItem),     // 33
    (I::None, O::Unit),                   // 34
    (I::Explicit, O::Unit),               // 35
    (I::Explicit, O::Unit),               // 36
    (I::None, O::Unit),                   // 37
    (I::Explicit, O::Unit),               // 38
    (I::None, O::Unit),                   // 39
    (I::Explicit, O::Unit),               // 40
    (I::Explicit, O::Unit),               // 41
    (I::None, O::Destination),            // 42
    (I::Explicit, O::UnitAndDestination), // 43
    (I::Explicit, O::Unit),               // 44
    (I::Explicit, O::Unit),               // 45
    (I::None, O::Unit),                   // 46
    (I::None, O::Unit),                   // 47
    (I::None, O::Unit),                   // 48
    (I::None, O::Unit),                   // 49
    (I::Explicit, O::Destination),        // 50
    (I::None, O::Unit),                   // 51
    (I::Explicit, O::Unit),               // 52
    (I::Explicit, O::Item),               // 53
    (I::Explicit, O::Item),               // 54
    (I::Explicit, O::Unit),               // 55
    (I::Explicit, O::Destination),        // 56
    (I::Explicit, O::Unit),               // 57
    (I::Explicit, O::Unit),               // 58
    (I::Explicit, O::Unit),               // 59
    (I::None, O::Unit),                   // 60
    (I::None, O::None),                   // 61
    (I::Explicit, O::Unit),               // 62
    (I::Explicit, O::Unit),               // 63
    (I::None, O::None),                   // 64
    (I::Explicit, O::Unit),               // 65
    (I::Explicit, O::Unit),               // 66
    (I::Explicit, O::Unit),               // 67
    (I::Explicit, O::Unit),               // 68
    (I::Explicit, O::UnitAndDestination), // 69
    (I::Explicit, O::Unit),               // 70
    (I::Explicit, O::Unit),               // 71
    (I::Explicit, O::Destination),        // 72
    (I::Explicit, O::Unit),               // 73
    (I::None, O::Unit),                   // 74
    (I::Explicit, O::Unit),               // 75
    (I::Explicit, O::Destination),        // 76
    (I::None, O::None),                   // 77
    (I::None, O::Unit),                   // 78
    (I::None, O::Unit),                   // 79
    (I::Explicit, O::Unit),               // 80
    (I::Explicit, O::Unit),               // 81
    (I::Explicit, O::Unit),               // 82
    (I::Explicit, O::UnitAndDestination), // 83
    (I::None, O::Unit),                   // 84
    (I::None, O::None),                   // 85
    (I::Explicit, O::GameObject),         // 86
    (I::Explicit, O::GameObject),         // 87
    (I::Explicit, O::GameObject),         // 88
    (I::Explicit, O::GameObject),         // 89
    (I::Explicit, O::Unit),               // 90
    (I::Explicit, O::Unit),               // 91
    (I::Explicit, O::Unit),               // 92
    (I::None, O::Unit),                   // 93
    (I::None, O::Unit),                   // 94
    (I::Explicit, O::Unit),               // 95
    (I::Explicit, O::Unit),               // 96
    (I::None, O::Unit),                   // 97
    (I::Explicit, O::Unit),               // 98
    (I::Explicit, O::Item),               // 99
    (I::Explicit, O::Unit),               // 100
    (I::Explicit, O::Item),               // 101
    (I::Explicit, O::Unit),               // 102
    (I::Explicit, O::Unit),               // 103
    (I::Explicit, O::Destination),        // 104
    (I::Explicit, O::Unit),               // 105
    (I::Explicit, O::Destination),        // 106
    (I::Explicit, O::Unit),               // 107
    (I::Explicit, O::Unit),               // 108
    (I::Explicit, O::Destination),        // 109
    (I::None, O::Unit),                   // 110
    (I::Explicit, O::Unit),               // 111
    (I::Explicit, O::Unit),               // 112
    (I::Explicit, O::Unit),               // 113
    (I::Explicit, O::Unit),               // 114
    (I::Explicit, O::Unit),               // 115
    (I::Explicit, O::CorpseEnemy),        // 116
    (I::Explicit, O::Unit),               // 117
    (I::None, O::Unit),                   // 118
    (I::Explicit, O::Unit),               // 119
    (I::Explicit, O::Unit),               // 120
    (I::Explicit, O::Unit),               // 121
    (I::None, O::None),                   // 122
    (I::Explicit, O::Unit),               // 123
    (I::Explicit, O::Unit),               // 124
    (I::Explicit, O::Unit),               // 125
    (I::Explicit, O::Unit),               // 126
    (I::Explicit, O::Item),               // 127
    (I::Explicit, O::Unit),               // 128
    (I::Explicit, O::Unit),               // 129
    (I::Explicit, O::Unit),               // 130
    (I::None, O::Unit),                   // 131
    (I::Explicit, O::Unit),               // 132
    (I::Explicit, O::Unit),               // 133
    (I::None, O::Unit),                   // 134
    (I::Explicit, O::Destination),        // 135
    (I::Explicit, O::Unit),               // 136
    (I::Explicit, O::Unit),               // 137
    (I::Explicit, O::Unit),               // 138
    (I::Explicit, O::Unit),               // 139
    (I::Explicit, O::Unit),               // 140
    (I::Explicit, O::Unit),               // 141
    (I::Explicit, O::Unit),               // 142
    (I::Explicit, O::Unit),               // 143
    (I::Explicit, O::UnitAndDestination), // 144
    (I::Explicit, O::UnitAndDestination), // 145
    (I::Explicit, O::Unit),               // 146
    (I::Explicit, O::Unit),               // 147
    (I::None, O::None),                   // 148
    (I::Explicit, O::Destination),        // 149
    (I::Explicit, O::Unit),               // 150
    (I::None, O::None),                   // 151
    (I::None, O::None),                   // 152
    (I::Explicit, O::Unit),               // 153
    (I::Explicit, O::Unit),               // 154
    (I::None, O::Unit),                   // 155
    (I::Explicit, O::Item),               // 156
    (I::Explicit, O::Unit),               // 157
    (I::Explicit, O::Item),               // 158
    (I::Explicit, O::Unit),               // 159
    (I::Explicit, O::Unit),               // 160
    (I::Explicit, O::Unit),               // 161
    (I::Explicit, O::Unit),               // 162
    (I::Explicit, O::Item),               // 163
    (I::Explicit, O::Unit),               // 164
    (I::Explicit, O::Unit),               // 165
    (I::Caster, O::Unit),                 // 166
    (I::Explicit, O::Unit),               // 167
    (I::Explicit, O::Unit),               // 168
    (I::Caster, O::Unit),                 // 169
    (I::Explicit, O::Unit),               // 170
    (I::None, O::Destination),            // 171
    (I::Explicit, O::CorpseAlly),         // 172
    (I::None, O::None),                   // 173
    (I::Explicit, O::Unit),               // 174
    (I::None, O::None),                   // 175
    (I::Explicit, O::Unit),               // 176
    (I::Explicit, O::Unit),               // 177
    (I::None, O::None),                   // 178
    (I::None, O::Destination),            // 179
    (I::None, O::None),                   // 180
    (I::Caster, O::Unit),                 // 181
    (I::None, O::None),                   // 182
    (I::None, O::None),                   // 183
    (I::Explicit, O::Unit),               // 184
    (I::None, O::None),                   // 185
    (I::None, O::None),                   // 186
    (I::Explicit, O::Unit),               // 187
    (I::Explicit, O::Destination),        // 188
    (I::Explicit, O::Unit),               // 189
    (I::Explicit, O::Unit),               // 190
    (I::Explicit, O::Unit),               // 191
    (I::Caster, O::Unit),                 // 192
    (I::Explicit, O::Unit),               // 193
    (I::None, O::None),                   // 194
    (I::None, O::Destination),            // 195
    (I::None, O::Destination),            // 196
    (I::None, O::Destination),            // 197
    (I::None, O::Destination),            // 198
    (I::Explicit, O::Unit),               // 199
    (I::None, O::None),                   // 200
    (I::None, O::None),                   // 201
    (I::Explicit, O::Unit),               // 202
    (I::Explicit, O::Unit),               // 203
    (I::Explicit, O::Unit),               // 204
    (I::Explicit, O::Unit),               // 205
    (I::Explicit, O::Item),               // 206
    (I::Explicit, O::Unit),               // 207
    (I::Explicit, O::Unit),               // 208
    (I::None, O::None),                   // 209
    (I::Explicit, O::Unit),               // 210
    (I::Explicit, O::Unit),               // 211
    (I::Explicit, O::Unit),               // 212
    (I::None, O::Destination),            // 213
    (I::Explicit, O::Unit),               // 214
    (I::Explicit, O::Unit),               // 215
    (I::Explicit, O::Unit),               // 216
    (I::Explicit, O::Unit),               // 217
    (I::None, O::None),                   // 218
    (I::None, O::Destination),            // 219
    (I::Explicit, O::Unit),               // 220
    (I::Explicit, O::Unit),               // 221
    (I::Explicit, O::Unit),               // 222
    (I::Explicit, O::Item),               // 223
    (I::Explicit, O::Unit),               // 224
    (I::Explicit, O::Unit),               // 225
    (I::Explicit, O::Unit),               // 226
    (I::Explicit, O::Unit),               // 227
    (I::None, O::None),                   // 228
    (I::None, O::None),                   // 229
    (I::Explicit, O::Unit),               // 230
    (I::Explicit, O::Unit),               // 231
    (I::Explicit, O::Unit),               // 232
    (I::None, O::None),                   // 233
    (I::None, O::Destination),            // 234
    (I::None, O::None),                   // 235
    (I::Explicit, O::Unit),               // 236
    (I::Explicit, O::Unit),               // 237
    (I::Explicit, O::Unit),               // 238
    (I::Explicit, O::Unit),               // 239
    (I::Explicit, O::Unit),               // 240
    (I::None, O::None),                   // 241
    (I::Explicit, O::Unit),               // 242
    (I::Explicit, O::Item),               // 243
    (I::Explicit, O::Unit),               // 244
    (I::None, O::None),                   // 245
    (I::None, O::None),                   // 246
    (I::None, O::None),                   // 247
    (I::None, O::None),                   // 248
    (I::Explicit, O::Unit),               // 249
    (I::Explicit, O::Unit),               // 250
    (I::Explicit, O::Unit),               // 251
    (I::Explicit, O::UnitAndDestination), // 252
    (I::Explicit, O::Unit),               // 253
    (I::None, O::Destination),            // 254
    (I::Explicit, O::Unit),               // 255
    (I::None, O::None),                   // 256
    (I::None, O::None),                   // 257
    (I::Explicit, O::Item),               // 258
    (I::Explicit, O::Item),               // 259
    (I::None, O::None),                   // 260
    (I::Explicit, O::Item),               // 261
    (I::None, O::None),                   // 262
    (I::Explicit, O::Item),               // 263
    (I::Explicit, O::Item),               // 264
    (I::Explicit, O::Unit),               // 265
    (I::Explicit, O::Item),               // 266
    (I::Caster, O::Unit),                 // 267
    (I::Explicit, O::Unit),               // 268
    (I::Explicit, O::Item),               // 269
    (I::Explicit, O::Unit),               // 270
    (I::Explicit, O::Unit),               // 271
    (I::Explicit, O::Unit),               // 272
    (I::Explicit, O::Item),               // 273
    (I::None, O::None),                   // 274
    (I::None, O::None),                   // 275
    (I::Explicit, O::Unit),               // 276
    (I::Explicit, O::Unit),               // 277
    (I::None, O::None),                   // 278
    (I::Explicit, O::Unit),               // 279
    (I::None, O::None),                   // 280
    (I::Explicit, O::Unit),               // 281
    (I::Explicit, O::Unit),               // 282
    (I::Explicit, O::Unit),               // 283
    (I::Explicit, O::Unit),               // 284
    (I::Explicit, O::Unit),               // 285
    (I::Explicit, O::Unit),               // 286
    (I::None, O::None),                   // 287
    (I::Explicit, O::Unit),               // 288
    (I::Explicit, O::Unit),               // 289
    (I::Explicit, O::Unit),               // 290
    (I::Explicit, O::Unit),               // 291
    (I::Explicit, O::Unit),               // 292
    (I::Explicit, O::Unit),               // 293
    (I::Explicit, O::Unit),               // 294
    (I::Explicit, O::Item),               // 295
    (I::Explicit, O::Item),               // 296
    (I::Explicit, O::Item),               // 297
    (I::Explicit, O::Unit),               // 298
    (I::None, O::None),                   // 299
    (I::None, O::None),                   // 300
    (I::Explicit, O::Item),               // 301
    (I::Explicit, O::None),               // 302
    (I::Explicit, O::Unit),               // 303
    (I::Explicit, O::Unit),               // 304
    (I::None, O::None),                   // 305
    (I::Explicit, O::Unit),               // 306
    (I::None, O::None),                   // 307
    (I::None, O::None),                   // 308
    (I::None, O::None),                   // 309
    (I::None, O::None),                   // 310
    (I::Explicit, O::Unit),               // 311
    (I::None, O::None),                   // 312
    (I::Explicit, O::Item),               // 313
    (I::None, O::None),                   // 314
    (I::Caster, O::Unit),                 // 315
    (I::Explicit, O::Unit),               // 316
    (I::Explicit, O::Unit),               // 317
    (I::None, O::None),                   // 318
    (I::None, O::None),                   // 319
    (I::None, O::None),                   // 320
    (I::None, O::None),                   // 321
    (I::None, O::None),                   // 322
    (I::None, O::None),                   // 323
    (I::None, O::None),                   // 324
    (I::None, O::None),                   // 325
    (I::None, O::None),                   // 326
    (I::None, O::None),                   // 327
    (I::None, O::None),                   // 328
    (I::None, O::None),                   // 329
    (I::None, O::None),                   // 330
    (I::None, O::None),                   // 331
    (I::None, O::None),                   // 332
    (I::None, O::None),                   // 333
    (I::None, O::None),                   // 334
    (I::Explicit, O::Unit),               // 335
    (I::Explicit, O::Unit),               // 336
    (I::Explicit, O::Unit),               // 337
    (I::Explicit, O::Unit),               // 338
    (I::None, O::None),                   // 339
    (I::None, O::None),                   // 340
    (I::Explicit, O::Unit),               // 341
    (I::None, O::None),                   // 342
    (I::None, O::None),                   // 343
    (I::None, O::None),                   // 344
    (I::None, O::None),                   // 345
    (I::None, O::None),                   // 346
    (I::None, O::None),                   // 347
    (I::None, O::None),                   // 348
    (I::None, O::None),                   // 349
    (I::None, O::None),                   // 350
    (I::None, O::None),                   // 351
    (I::None, O::None),                   // 352
    (I::None, O::Destination),            // 353
    (I::None, O::None),                   // 354
    (I::None, O::None),                   // 355
    (I::None, O::None),                   // 356
    (I::Explicit, O::Item),               // 357
    (I::Explicit, O::Item),               // 358
    (I::Explicit, O::Item),               // 359
    (I::Explicit, O::Item),               // 360
];
