//! Entity update bridge regression scenarios.
//!
//! Separated from the entity_update_bridge.rs root under #662.

use super::*;
use wow_core::ObjectGuid;
use wow_entities::{
    ACTIVE_PLAYER_DATA_COINAGE_BIT, ACTIVE_PLAYER_DATA_EXPLORED_ZONES_FIRST_BIT,
    ACTIVE_PLAYER_DATA_EXPLORED_ZONES_PARENT_BIT, ACTIVE_PLAYER_DATA_HEIRLOOM_FLAGS_BIT,
    ACTIVE_PLAYER_DATA_HEIRLOOMS_BIT, ACTIVE_PLAYER_DATA_HONOR_BIT,
    ACTIVE_PLAYER_DATA_HONOR_NEXT_LEVEL_BIT, ACTIVE_PLAYER_DATA_HONOR_PARENT_BIT,
    ACTIVE_PLAYER_DATA_PARENT_BIT, ACTIVE_PLAYER_DATA_QUEST_COMPLETED_FIRST_BIT,
    ACTIVE_PLAYER_DATA_QUEST_COMPLETED_PARENT_BIT, ACTIVE_PLAYER_DATA_REST_INFO_FIRST_BIT,
    ACTIVE_PLAYER_DATA_REST_INFO_PARENT_BIT, ACTIVE_PLAYER_DATA_SCALING_PLAYER_LEVEL_DELTA_BIT,
    ACTIVE_PLAYER_DATA_SCALING_PLAYER_LEVEL_DELTA_PARENT_BIT, ACTIVE_PLAYER_DATA_TOYS_BIT,
    ACTIVE_PLAYER_DATA_TRANSMOG_BIT, ACTIVE_PLAYER_DATA_WATCHED_FACTION_INDEX_BIT,
    AREA_TRIGGER_DATA_DURATION_BIT, AREA_TRIGGER_DATA_PARENT_BIT, Bag,
    CONTAINER_DATA_NUM_SLOTS_BIT, CONVERSATION_DATA_LAST_LINE_END_TIME_BIT,
    CONVERSATION_DATA_PARENT_BIT, CORPSE_DATA_CUSTOMIZATIONS_BIT, CORPSE_DATA_DISPLAY_ID_BIT,
    CORPSE_DATA_PARENT_BIT, ConversationLine, Corpse, CorpseCustomizationChoice, CorpseType,
    DYNAMIC_OBJECT_DATA_PARENT_BIT, DYNAMIC_OBJECT_DATA_RADIUS_BIT, DynamicObject,
    GAME_OBJECT_DATA_CREATED_BY_BIT, GAME_OBJECT_DATA_DISPLAY_ID_BIT, GAME_OBJECT_DATA_PARENT_BIT,
    GameObject, ITEM_DATA_STACK_COUNT_BIT, Item, PLAYER_DATA_FLAGS_BIT,
    PLAYER_DATA_HONOR_LEVEL_BIT, PLAYER_DATA_PARENT_BIT, PLAYER_DATA_PARTY_TYPE_FIRST_BIT,
    PLAYER_DATA_PARTY_TYPE_PARENT_BIT, PLAYER_DATA_PLAYER_TITLE_BIT, Player,
    SCENE_OBJECT_DATA_PARENT_BIT, SCENE_OBJECT_DATA_SCRIPT_PACKAGE_ID_BIT, SceneObject,
    UNIT_DATA_EMOTE_STATE_BIT, UNIT_DATA_HEALTH_BIT, UNIT_DATA_MODS_PARENT_BIT,
    UNIT_DATA_PARENT_BIT, UNIT_DATA_STAND_STATE_BIT, UNIT_DATA_STAND_STATE_PARENT_BIT,
    UNIT_DATA_VIRTUAL_ITEMS_FIRST_BIT, UNIT_DATA_VIRTUAL_ITEMS_PARENT_BIT, VisibleItemValues,
};
use wow_packet::ServerPacket;

fn mask_has(mask: &[u32], bit: usize) -> bool {
    (mask[bit / 32] & (1 << (bit % 32))) != 0
}

fn mask_has_u64(mask: u64, bit: usize) -> bool {
    (mask & (1u64 << bit)) != 0
}

mod scenarios_1;
mod scenarios_2;
