//! Values delta packets.
//!
//! Separated from unit.rs under #689.

use super::*;

#[derive(Debug, Clone, PartialEq)]
pub struct UnitDataValuesDeltaUpdate {
    pub changed_object_type_mask: u32,
    pub object_data: Option<ObjectDataValuesUpdate>,
    pub unit_data_mask: [u32; 8],
    pub state_world_effect_ids: Vec<u32>,
    pub passive_spells: Vec<PassiveSpellHistoryValuesUpdate>,
    pub passive_spells_update_mask: Option<Vec<u32>>,
    pub world_effects: Vec<i32>,
    pub world_effects_update_mask: Option<Vec<u32>>,
    pub channel_objects: Vec<ObjectGuid>,
    pub channel_objects_update_mask: Option<Vec<u32>>,
    pub health: i64,
    pub max_health: i64,
    pub display_id: i32,
    pub state_spell_visual_id: u32,
    pub state_anim_id: u32,
    pub state_anim_kit_id: u32,
    pub charm: ObjectGuid,
    pub summon: ObjectGuid,
    pub critter: ObjectGuid,
    pub charmed_by: ObjectGuid,
    pub summoned_by: ObjectGuid,
    pub created_by: ObjectGuid,
    pub demon_creator: ObjectGuid,
    pub look_at_controller_target: ObjectGuid,
    pub target: ObjectGuid,
    pub battle_pet_companion_guid: ObjectGuid,
    pub battle_pet_db_id: u64,
    pub channel_data: UnitChannelValuesUpdate,
    pub summoned_by_home_realm: u32,
    pub race: u8,
    pub class_id: u8,
    pub player_class_id: u8,
    pub sex: u8,
    pub display_power: u8,
    pub override_display_power_id: u32,
    pub level: i32,
    pub effective_level: i32,
    pub content_tuning_id: i32,
    pub scaling_level_min: i32,
    pub scaling_level_max: i32,
    pub scaling_level_delta: i32,
    pub scaling_faction_group: i32,
    pub scaling_health_item_level_curve_id: i32,
    pub scaling_damage_item_level_curve_id: i32,
    pub faction_template: i32,
    pub flags: u32,
    pub flags2: u32,
    pub flags3: u32,
    pub aura_state: u32,
    pub ranged_attack_round_base_time: u32,
    pub bounding_radius: f32,
    pub combat_reach: f32,
    pub display_scale: f32,
    pub native_display_id: i32,
    pub native_display_scale: f32,
    pub mount_display_id: i32,
    pub min_damage: f32,
    pub max_damage: f32,
    pub min_off_hand_damage: f32,
    pub max_off_hand_damage: f32,
    pub stand_state: u8,
    pub pet_talent_points: u8,
    pub vis_flags: u8,
    pub anim_tier: u8,
    pub pet_number: u32,
    pub pet_name_timestamp: u32,
    pub pet_experience: u32,
    pub pet_next_level_experience: u32,
    pub mod_casting_speed: f32,
    pub mod_spell_haste: f32,
    pub mod_haste: f32,
    pub mod_ranged_haste: f32,
    pub mod_haste_regen: f32,
    pub mod_time_rate: f32,
    pub created_by_spell: i32,
    pub emote_state: i32,
    pub training_points_used: i16,
    pub training_points_total: i16,
    pub base_mana: i32,
    pub base_health: i32,
    pub sheathe_state: u8,
    pub pvp_flags: u8,
    pub pet_flags: u8,
    pub shapeshift_form: u8,
    pub attack_power: i32,
    pub attack_power_mod_pos: i32,
    pub attack_power_mod_neg: i32,
    pub attack_power_multiplier: f32,
    pub ranged_attack_power: i32,
    pub ranged_attack_power_mod_pos: i32,
    pub ranged_attack_power_mod_neg: i32,
    pub ranged_attack_power_multiplier: f32,
    pub set_attack_speed_aura: i32,
    pub lifesteal: f32,
    pub min_ranged_damage: f32,
    pub max_ranged_damage: f32,
    pub max_health_modifier: f32,
    pub hover_height: f32,
    pub min_item_level_cutoff: i32,
    pub min_item_level: i32,
    pub max_item_level: i32,
    pub wild_battle_pet_level: i32,
    pub battle_pet_companion_name_timestamp: u32,
    pub interact_spell_id: i32,
    pub scale_duration: i32,
    pub looks_like_mount_id: i32,
    pub looks_like_creature_id: i32,
    pub look_at_controller_id: i32,
    pub perks_vendor_item_id: i32,
    pub guild_guid: ObjectGuid,
    pub skinning_owner_guid: ObjectGuid,
    pub flight_capability_id: i32,
    pub glide_event_speed_divisor: f32,
    pub current_area_id: u32,
    pub combo_target: ObjectGuid,
    pub npc_flags: [u32; 2],
    pub power_regen_flat_modifier: [f32; 10],
    pub power_regen_interrupted_flat_modifier: [f32; 10],
    pub power: [i32; 10],
    pub max_power: [i32; 10],
    pub mod_power_regen: [f32; 10],
    pub virtual_items: [VisibleItemValuesUpdate; 3],
    pub attack_round_base_time: [u32; 2],
    pub stats: [i32; 5],
    pub stat_pos_buff: [i32; 5],
    pub stat_neg_buff: [i32; 5],
    pub resistances: [i32; 7],
    pub power_cost_modifier: [i32; 7],
    pub power_cost_multiplier: [f32; 7],
    pub resistance_buff_mods_positive: [i32; 7],
    pub resistance_buff_mods_negative: [i32; 7],
}

impl Default for UnitDataValuesDeltaUpdate {
    fn default() -> Self {
        Self {
            changed_object_type_mask: VALUES_TYPE_UNIT,
            object_data: None,
            unit_data_mask: [0; 8],
            state_world_effect_ids: Vec::new(),
            passive_spells: Vec::new(),
            passive_spells_update_mask: None,
            world_effects: Vec::new(),
            world_effects_update_mask: None,
            channel_objects: Vec::new(),
            channel_objects_update_mask: None,
            health: 0,
            max_health: 0,
            display_id: 0,
            state_spell_visual_id: 0,
            state_anim_id: 0,
            state_anim_kit_id: 0,
            charm: ObjectGuid::EMPTY,
            summon: ObjectGuid::EMPTY,
            critter: ObjectGuid::EMPTY,
            charmed_by: ObjectGuid::EMPTY,
            summoned_by: ObjectGuid::EMPTY,
            created_by: ObjectGuid::EMPTY,
            demon_creator: ObjectGuid::EMPTY,
            look_at_controller_target: ObjectGuid::EMPTY,
            target: ObjectGuid::EMPTY,
            battle_pet_companion_guid: ObjectGuid::EMPTY,
            battle_pet_db_id: 0,
            channel_data: UnitChannelValuesUpdate::default(),
            summoned_by_home_realm: 0,
            race: 0,
            class_id: 0,
            player_class_id: 0,
            sex: 0,
            display_power: 0,
            override_display_power_id: 0,
            level: 0,
            effective_level: 0,
            content_tuning_id: 0,
            scaling_level_min: 0,
            scaling_level_max: 0,
            scaling_level_delta: 0,
            scaling_faction_group: 0,
            scaling_health_item_level_curve_id: 0,
            scaling_damage_item_level_curve_id: 0,
            faction_template: 0,
            flags: 0,
            flags2: 0,
            flags3: 0,
            aura_state: 0,
            ranged_attack_round_base_time: 0,
            bounding_radius: 0.0,
            combat_reach: 0.0,
            display_scale: 0.0,
            native_display_id: 0,
            native_display_scale: 0.0,
            mount_display_id: 0,
            min_damage: 0.0,
            max_damage: 0.0,
            min_off_hand_damage: 0.0,
            max_off_hand_damage: 0.0,
            stand_state: 0,
            pet_talent_points: 0,
            vis_flags: 0,
            anim_tier: 0,
            pet_number: 0,
            pet_name_timestamp: 0,
            pet_experience: 0,
            pet_next_level_experience: 0,
            mod_casting_speed: 0.0,
            mod_spell_haste: 0.0,
            mod_haste: 0.0,
            mod_ranged_haste: 0.0,
            mod_haste_regen: 0.0,
            mod_time_rate: 0.0,
            created_by_spell: 0,
            emote_state: 0,
            training_points_used: 0,
            training_points_total: 0,
            base_mana: 0,
            base_health: 0,
            sheathe_state: 0,
            pvp_flags: 0,
            pet_flags: 0,
            shapeshift_form: 0,
            attack_power: 0,
            attack_power_mod_pos: 0,
            attack_power_mod_neg: 0,
            attack_power_multiplier: 0.0,
            ranged_attack_power: 0,
            ranged_attack_power_mod_pos: 0,
            ranged_attack_power_mod_neg: 0,
            ranged_attack_power_multiplier: 0.0,
            set_attack_speed_aura: 0,
            lifesteal: 0.0,
            min_ranged_damage: 0.0,
            max_ranged_damage: 0.0,
            max_health_modifier: 0.0,
            hover_height: 0.0,
            min_item_level_cutoff: 0,
            min_item_level: 0,
            max_item_level: 0,
            wild_battle_pet_level: 0,
            battle_pet_companion_name_timestamp: 0,
            interact_spell_id: 0,
            scale_duration: 0,
            looks_like_mount_id: 0,
            looks_like_creature_id: 0,
            look_at_controller_id: 0,
            perks_vendor_item_id: 0,
            guild_guid: ObjectGuid::EMPTY,
            skinning_owner_guid: ObjectGuid::EMPTY,
            flight_capability_id: 0,
            glide_event_speed_divisor: 0.0,
            current_area_id: 0,
            combo_target: ObjectGuid::EMPTY,
            npc_flags: [0; 2],
            power_regen_flat_modifier: [0.0; 10],
            power_regen_interrupted_flat_modifier: [0.0; 10],
            power: [0; 10],
            max_power: [0; 10],
            mod_power_regen: [0.0; 10],
            virtual_items: [VisibleItemValuesUpdate::default(); 3],
            attack_round_base_time: [0; 2],
            stats: [0; 5],
            stat_pos_buff: [0; 5],
            stat_neg_buff: [0; 5],
            resistances: [0; 7],
            power_cost_modifier: [0; 7],
            power_cost_multiplier: [0.0; 7],
            resistance_buff_mods_positive: [0; 7],
            resistance_buff_mods_negative: [0; 7],
        }
    }
}

pub(super) fn unit_mask_has(data: &UnitDataValuesDeltaUpdate, bit: usize) -> bool {
    let block = bit / 32;
    let offset = bit % 32;
    data.unit_data_mask.get(block).copied().unwrap_or(0) & (1 << offset) != 0
}
