use wow_data::forever_birth::{item_records::ItemRecord, item_sparse::SparseItemRecord};
pub(super) fn basic(id: u32) -> ItemRecord {
    ItemRecord {
        id,
        class: 4,
        subclass: 1,
        material: 0,
        inventory_type: 5,
        sheathe: 0,
        pet_food: 0,
        sound_override: 0,
        icon_file: 0,
        group_sounds: 0,
        content_tuning: 0,
        modified_crafting_reagent: 0,
        unknown_1200: 0,
        crafting_quality: 0,
        squish_era: 0,
        recraft_reagent_percentage: 0.0,
        order_source: 0,
    }
}
pub(super) fn sparse(id: u32) -> SparseItemRecord {
    SparseItemRecord {
        id,
        strings: Default::default(), // Synthetic source's empty localized slots.
        expansion: 0,
        damage_variance: 0.0,
        limit_category: 0,
        duration: 0,
        quality_modifier: 0.0,
        bag_family: 0,
        start_quest: 0,
        language: 0,
        item_range: 0.0,
        socket_percentage: [0.0; 10],
        stat_percent: [0; 10],
        stat_bonus: [-1; 10],
        stackable: 1,
        max_count: 0,
        min_reputation: 0,
        required_ability: 0,
        allowable_race: u64::MAX,
        sell_price: 0,
        buy_price: 0,
        vendor_stack: 1,
        price_variance: 0.0,
        price_random: 0.0,
        flags: [0; 5],
        faction_related: 0,
        modified_crafting_reagent: 0,
        content_tuning: 0,
        player_level_curve: 0,
        item_level_offset_curve: 0,
        item_level_offset: 0,
        squish_era: 0,
        name_description: 0,
        transmog_holiday: 0,
        holiday: 0,
        gem_properties: 0,
        socket_enchantment: 0,
        totem_category: 0,
        instance_bound: 0,
        zone_bound: [0; 2],
        item_set: 0,
        lock: 0,
        page: 0,
        delay: 0,
        min_faction: 0,
        required_skill_rank: 0,
        required_skill: 0,
        item_level: 1,
        allowable_class: -1,
        artifact: 0,
        spell_weight: 0,
        spell_weight_category: 0,
        socket_type: [0; 3],
        sheathe: 0,
        material: 0,
        page_material: 0,
        bonding: 0,
        damage_type: 0,
        container_slots: 0,
        required_pvp_medal: 0,
        required_pvp_rank: 0,
        required_level: 1,
        inventory_type: 5,
        quality: 0,
        ammunition: 0,
    }
}
